### ISSUE TITLE
Id filter is removed when other filters are used 

### ISSUE THREAD

**Issue by JawHawk** [sosy-lab/benchexec#1015]
Due to some very recent commits, id filter gets removed when other filters are applied. Also there is a very abrupt reload and search bar gets out of focused. Attached is the video of the same.

https://github.com/sosy-lab/benchexec/assets/86140365/ca83eb9a-7f29-4ea2-a78e-0c98392fbfdc

I am interested in fixing this along with #806 . Thorough testing is required before commits to avoid such unnecessary breaks.

**Comment by PhilippWendler** [comment]
Ow, thanks for noticing! Any help would be appreciated.
