### ISSUE TITLE
Add Reset Button to the scatter and quantile plot webpage

### ISSUE THREAD

**Issue by Mariem5005** [sosy-lab/benchexec#1018]
Can we consider adding a reset button to the scatter and quantile plot webpage?
The reset button will provide a convenient way for users to revert the graph to its original state, resetting all modifications made through the dropdown list.
https://sosy-lab.github.io/benchexec/example-table/svcomp-simple-cbmc-cpachecker.table.html#/scatter

**Comment by PhilippWendler** [comment]
Yes, I would say this is a nice idea.

**Comment by JawHawk** [comment]
Can I work on this ?

**Comment by PhilippWendler** [comment]
Sure, AFAIK there is nobody working on it right now.
