### ISSUE TITLE
hyperlink is not visible in info page

### ISSUE THREAD

**Issue by Mariem5005** [sosy-lab/benchexec#1026]
![bug](https://github.com/sosy-lab/benchexec/assets/145173084/c18bfcf9-41e6-4cd3-8498-f0291af2d87d)
the hyperlink is not visible in info page in 
https://sosy-lab.github.io/benchexec/example-table/svcomp-simple-cbmc-cpachecker.table.html#/info

**Comment by Mariem5005** [comment]
sorry for the confusion
- "click here to view them" is not clickable
-  the link is not visible until you select all the text like this
![bug2](https://github.com/sosy-lab/benchexec/assets/145173084/e8d8ffd2-f1e8-49de-905a-35f61fa7db71)

**Comment by PhilippWendler** [comment]
@Mariem5005 ?
