### ISSUE TITLE
Incosistent file endings in Toolinfo modules

### ISSUE THREAD

**Issue by marian-lingsch** [sosy-lab/benchexec#1092]
Currently it seems that different tool info modules are using different line endings. For example `jcwit` uses `CRLF` but `CPAchecker` uses `LF`.

If this is not desired maybe a CI check may be useful to catch this in the future.

**Comment by PhilippWendler** [comment]
Thanks. I would have thought that black handles that, but apparently it only ensures that all line endings in a file are consistent, and a feature request to force specific line endings was rejected. I do want consistent line endings, but given that it has happened only once so far (I did not find any other occurrence than `jcwit.py`), I also do not want to maintain another CI check if black cannot do it. So I will just fix it now manually and wait for the second time it happens.
