### ISSUE TITLE
Human-readable memory consumption

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/benchexec#127]
Hi,

For benchexec tables I find it very difficult to read memory usage values like "3442581504".
I can only assume it's bytes (units are written in the brackets for time, but not for memUsage!) and I would much rather prefer something like "3.5GB".
Most unix tools have this ability, e.g. check `du -h`

**Comment by leostrakosch** [comment]
Hey,

currently this can be achieved by using the column attributes **displayUnit** and **scaleFactor**

The following example from the table-generator documentation changes the memUsage values to MB:
<column title="memUsage" displayUnit="MB" scaleFactor="0.000001"/>

(see https://github.com/sosy-lab/benchexec/blob/master/doc/table-generator.md)

**Comment by cheshire** [comment]
Right thanks, I assume it can be closed then.
