### ISSUE TITLE
Table-generator has formatting issues related to shared state

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#128]
When replacing the usage of `concurrent.futures.ProcessPoolExecutor` with `concurrent.futures.ThreadPoolExecutor` or with `Util.DummyExecutor`, the output of table-generator changes with regard to some formatting of HTML table values.

I do not know which of the two behaviors is the correct one, but clearly this is unintended.
I suspect it is the case because some of the `Column` objects get modified, and when there are multiple copies of these objects (one in each worker process), the behavior is different from the case where we have shared instances among all worker threads.

**Comment by leostrakosch** [comment]
0738777 should fix this.

The behavior of the parallel execution was the correct one.
Just as you suspected, the use of multiple copies of these objects in the different worker processes covered a bug.

All integration tests and some additional ones worked, if you agree with the new behavior the issue could be closed.

**Comment by PhilippWendler** [comment]
Thank you very much!
