### ISSUE TITLE
Verification tasks with multiple results for single run

### ISSUE THREAD

**Issue by stahlbauer** [sosy-lab/benchexec#143]
The current implementation of BenchExec does not support multiple properties per file. Having support for this feature would be nice. 

- [ ] Clarify: Should this feature get introduced into BenchExech?
- [ ] Clarify: Which format should be used to express the mapping of properties to expected results?
- [ ] Clarify: How should we consider different entry functions?
- [ ] Clarify: How should the result for multiple properties get presented in the final report?
- [ ] Implement the feature and make it available to the mainline of BenchExec.

**Comment by PhilippWendler** [comment]
What exactly do you mean with "multiple properties per file"?

BenchExec does have support for multiple properties per file. You can for example have a file that has a known reachability counterexample and terminates, and is marked with `_false-unreach-call_true-termination` in the file name. Then BenchExec uses the respective property depending on what is declared in the property file that the user specified for the current benchmark.
If you have tables where different properties are used for different verification tasks, a column appears that lists the property of each task.

So as far as I understand the first, second, and fourth points of your list are solved and implemented. For different entry functions nothing is supported yet. Doing so would largely depend on defining how the expected results per entry function should be given. In any case if there is demand for this and it is a generally useful feature I would like to invite contributions for adding this to BenchExec.

**Comment by stahlbauer** [comment]
This issue focuses on scenarios where BenchExec is used to run a software model checker for verifying a set of properties of a given program (C file with a specific entry function). 

We express a property as finite automata (safety properties), that is, separately from the file to verify (the specification is not instrumented into the program). There might be thousands of this properties that are relevant for a given program (for example, in case of test generation). In case of the Linux kernel, there are hundreds of properties that specify the correct usage of its API. 

Using the file name to encode the expected results is very limited by to the limited length of the file name. The expected result might also be conditional (only for specific environments/machine models/...).

**Comment by PhilippWendler** [comment]
So this is not about just having multiple properties per file, but a large amount of them.

How do you suggest to handle this?

@delcypher has developed https://github.com/delcypher/svcomp-build-mockup, which, among other things, seems to include a format for specifying multiple verification tasks per file, though I am not sure whether it is appropriate for you.

**Comment by stahlbauer** [comment]
Some suggestions (which I would implement if we can agree on a way of doing it): 
- Each tool should be able to parse its output for the results per property. 
- For each program, we can provide a separate file with the expected verdicts per property. 
- Each property has to be identified by a unique string (the only requirement is that the tool has to provide its results with the same schema for property names).

**Comment by stahlbauer** [comment]
Other (industrial) users of

**Comment by PhilippWendler** [comment]
For parsing the result, I do not understand why this needs to be changed?

How should the file with the expected verdict per property should look like? What format should it have?

**Comment by delcypher** [comment]
@stahlbauer 
It would be good to not reinvent the wheel here. I created the mock up benchmark specification format to solve the exact problem (and several others) that you are currently experiencing. Using the file name to state verification properties is far too cumbersome. I'm not actively developing the mock up right now because the SV-COMP community did not not show much interest in it.

There was a proposal for the new system to appear as a demo category in SV-COMP but I am currently too busy to incorporate my work.

**Comment by stahlbauer** [comment]
@delcypher 
I like the format for specifying verification tasks, and the expected results, that is used by the mockup. So we should use it. Does the mockup also provide a replacement for table-generator.py which uses the reference results in this files?

**Comment by stahlbauer** [comment]
@PhilippWendler 
Each tool can provide its results for the different properties in a different format. This is the reason why we should a separate parser for this. At least, the current implementation for parsing the output has to be adjusted such that it supports parsing results for different properties.

**Comment by stahlbauer** [comment]
Here is an example of CPAcheckers current output for sets of properties:
```
Verification result: FALSE. Property violation (1, 12, 2, 3, 4, 7, 8, 5, 6, 11, 9) found by chosen configuration.
	Number of considered properties: 12
	Number of violated properties: 11
	Number of conditional violated properties: 0
	Number of unknown properties: 0
	Number of satisfied properties: 1
	Number of relevant properties: 6
	Status by property:
		Property 1: FALSE (relevant) 		N25->N26 with '' in line 0
		Property 11: FALSE 		N5->N7 with '' in line 14
		Property 12: FALSE 		N36->N37 with '' in line 0
		Property 2: FALSE (relevant) 		N28->N29 with 'int y;' in line 35
		Property 3: FALSE (relevant) 		N30->N31 with 'int z;' in line 36
		Property 4: FALSE (relevant) 		N33->N24 with 'return 0;' in line 40
		Property 5: FALSE 		N1->N2 with '' in line 0
		Property 6: FALSE 		N9->N13 with '' in line 19
		Property 7: FALSE 		N15->N0 with 'return z;' in line 29
		Property 8: FALSE 		N17->N21 with '' in line 26
		Property 9: FALSE (relevant) 		N18->N19 with '' in line 24
		Property 10: TRUE (relevant) 		N10->N11 with '' in line 17
```

**Comment by stahlbauer** [comment]
The task-definition file could look similar to this:
```
architectures:
  - x86_64
  - i686
categories:
  - examples
language: c99
memory_model: precise
name: bad_unsigned_overflow32_example
schema_version: 0
sources:
  - main.c
verification_tasks:
  Property 1:
    correct: false
  Property 2:
    correct: false
  Property 3:
    correct: false
  Property 4:
    correct: false
  Property 5:
    correct: false
  Property 6:
    correct: false
  Property 7:
    correct: false
  Property 8:
    correct: false
  Property 9:
    correct: false
  Property 10:
    correct: true
  Property 11:
    correct: false
  Property 12:
    correct: false
comments: |
  This benchmark asserts that an unsigned 32-bit integer
  saturates when trying to overflow. This is incorrect
  and the assert should fail.
```

**Comment by PhilippWendler** [comment]
Ah, so you want to have multiple (many) properties checked and reported in a *single* run? This is yet something different than what I understood from your description.

Before discussing an implementation of this, we would have do discuss what we actually want for this use case. How would you envision the results to be presented in the tables for example? A separate row for each tuple of input program and property? A single row with lots of columns like `status Property 1`, `status Property 2` etc.? There are several features that rely on classifying run results into `correct` etc., e.g. for statistics. How do we handle these?

**Comment by stahlbauer** [comment]
I would propose to provide an alternative implementation of table-generator.py which could be the base of our discussion. Having several lines for a property does not make much sense to me (it is hard to map the effort---for example the CPU time---to properties). I would propose to have an overall verdict for the specification (having one violated property means that the full specification is violated), and details on the different properties. To make the diffs between verification runs correctly, we should not compare the numbers of correct/violated properties but the result for each property individually (but this is independent of the presentation in the report).

**Comment by PhilippWendler** [comment]
Ok, so having one main result and the rest just as additional information makes things easier.

I think we should get a working prototype by returning the main result from `determine_result` and a value for each property from `get_value_from_output` in the tool-info module (the cell value does not need to be numeric, it can be text as well). No changes to table-generator would be necessary. You could try this?

For diff, we have the possibility to specify columns as "relevant for diff", this would solve it.

**Comment by stahlbauer** [comment]
Sounds great. I will take care of it...

**Comment by stahlbauer** [comment]
@PhilippWendler 
Your solution works in cases where we have a fixed set of properties (for example, the LDV rules) that is used for all programs in the benchmark suite.
