### ISSUE TITLE
Update test framework

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#162]
Currently the tests are executed with `nose`, but this framework is dead. We should switch to a new framework, for example `nose2` or `py.test`.

It seems `py.test` has quite useful support for fixtures and parameterized tests, not sure whether `nose2` also supports this.

**Comment by PhilippWendler** [comment]
Furthermore, `setup.py test` is [deprecated](https://setuptools.readthedocs.io/en/latest/userguide/commands.html#test-build-package-and-run-a-unittest-suite) and will be removed in the future. We might just tell people to use the command of the test framework that we decide on, or use [tox](https://tox.readthedocs.io/en/latest/).

**Comment by PhilippWendler** [comment]
Problems I found while investigating:
- We have tests directly in packages (in `__init__.py`), but nose2 and other testing frameworks do not support this.
- We have test modules with names that are not globally unique (e.g., `test_integration`), this also seems problematic for many testing frameworks.
- We have tests below `contrib/`, but `contrib/` is not a proper package (and shouldn't be).

**Comment by Mihan786Chistie** [comment]
Hi, can you explain what we need to do to fix the issue, I am a beginner so I am having trouble understanding.

**Comment by PhilippWendler** [comment]
As a first step, an appropriate framework needs to be chosen. This should be done systematically based on criteria like ease of use, how common the framework is, whether it is well maintained etc. Next, the framework needs to be integrated in BenchExec's project structure and the existing tests need to adjusted where necessary. This might also include restructuring the tests and in general improving their state because as mentioned above, the current test infrastructure might be problematic for some test frameworks.

**Comment by samadpls** [comment]
hey @PhilippWendler 
I'm interested in contributing to help address these problems. I have experience with Python and I'm excited to use my skills to improve the testing framework of the project.

I understand that the current testing framework uses nose, which is no longer maintained. I agree that it would be a good idea to evaluate alternative testing frameworks like nose2 or py.test, and I'd be happy to help with this evaluation process. Additionally, I'd like to contribute to improving the current test infrastructure, such as restructuring tests that are problematic for the new framework and adjusting existing tests where necessary.

Please let me know if there are any specific tasks related to the testing infrastructure that I can work on. I'm excited to be part of the project and contribute to its success.

Also, could you provide me with more details about the project and how I can contact you or the team to get started?

Thank you for considering my interest in contributing.

**Comment by Naman-Priyadarshi** [comment]
I have created a new discussion related to this topic as it can easy to find for everyone instead of under an issue

**Comment by PhilippWendler** [comment]
Yes, please let's keep this issue focused on actual discussion of the migration to a new test framework. Any more general discussions, including personal introductions, GSoC projects, etc. should be done in the [GitHub Discussions](https://github.com/sosy-lab/benchexec/discussions).

**Comment by Kanchan9m** [comment]
Hi, Can you explain what we need to fix the issue, I am a beginner so I have some problems to understanding.

**Comment by PhilippWendler** [comment]
There are some concrete problems listed above and there is also a discussion about this in https://github.com/sosy-lab/benchexec/discussions/903. If you have any further concrete questions, please ask them. Questions about the concrete issue should be posted here, more general questions in the discussion.
