### ISSUE TITLE
Load zip.js from CDN instead of sosy-lab.org

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#195]
All Javascript libraries except zip.js are loaded from the JSDelivr CDN, because the latter has an older version of zip.js with missing files. As soon as an updated version is available, we want to switch to the CDN (also because using a different domain currently breaks the `--offline` flag).

This depends on https://github.com/gildas-lormeau/zip.js/issues/137#issuecomment-173612814 and probably https://github.com/gildas-lormeau/zip.js/issues/145.

**Comment by danieldietsch** [comment]
It would be nice if we were able to specify from where the .js files should be loaded. We would like to host them locally so we do not have to rely on CDNs.

**Comment by PhilippWendler** [comment]
@danieldietsch Does `table-generator --offline` what you want?

**Comment by danieldietsch** [comment]
Oh I never noticed that. This looks like the option I want. 
Two questions:
* Is there some place where I could download the current content of ``lib/javascript``? 
* Would it be difficult to add an option that allows me to specify a different path to the lib folder?

**Comment by PhilippWendler** [comment]
There is currently no automated way to download the libs, but you can have a look at `grep lib_url benchexec/tablegenerator/template.html`.

However, I just noticed that additionally we load fonts from Google and one library from `sosy-lab.org`, because it is not available on the CDN (#195). Setting `--offline` currently has no effect on these. It could be made to work, but providing the fonts locally seems a little bit more complicated than for the JS libs.

Adding an option that specifies the URL would not be complicated, just add the option and change this line to retrieve the URL from `options` if specified there:
https://github.com/sosy-lab/benchexec/blob/9b409e4dc418fd89db66dfc1243eb494b98da844/benchexec/tablegenerator/__init__.py#L1320
Would you like to send a PR?

**Comment by danieldietsch** [comment]
Yes, I will have a look -- but its not too important, so I might take some time.
