### ISSUE TITLE
Fix table-generator statistics for unconfirmed results

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#201]
The code from https://github.com/sosy-lab/benchexec/commit/bb65978e3075285f41a11ad8f26b16d9bb64eedb is not understandable, very hacky, and probably wrong, it needs to be improved.

I suspect it is wrong if there are multiple run results, some without and some with unconfirmed results.

**Comment by PhilippWendler** [comment]
Ah, and tests for this should also be added, in a similar way like the existing integration tests for table-generator.

**Comment by leostrakosch** [comment]
Tests were added in acc2092 and c2388e7 .
Are these sufficient for you?

**Comment by PhilippWendler** [comment]
Yes, thank you.
