### ISSUE TITLE
Drop support for Python 3.2 and maybe Python 3.3?

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#207]
Currently BenchExec supports Python 3.2 and newer.

There are a number of improvements in Python 3.3 that would be nice to have, e.g. the [reworked I/O exception hierarchy](https://docs.python.org/3/whatsnew/3.3.html#pep-3151), an [improved `bz2` module](https://docs.python.org/3/whatsnew/3.3.html#bz2), [`time.monotonic()`](https://docs.python.org/3/whatsnew/3.3.html#time) etc.

Platforms that only have Python 3.2 are:
- Ubuntu 12.04, which goes out of support in April 2017
- Debian Wheezy (oldstable), which is out of regular support and loses LTS support in May 2018

We expect that in the future most users want to make use of containers anyway, and Debian Wheezy has Linux 3.2 without container support. So April 2017 after Ubuntu 12.04 goes out of support could be a good opportunity to drop support for Python 3.2.

Because both Ubuntu 14.04 and Debian Jessie (stable) already have Python 3.4, we could maybe even drop support for Python 3.3 at the same time. Python 3.4 also has a number of nice improvements ([enums](https://docs.python.org/3/whatsnew/3.4.html#enum), [pathlib](https://docs.python.org/3/whatsnew/3.4.html#pathlib), [statistics](https://docs.python.org/3/whatsnew/3.4.html#statistics)).

The support of `runexec` for Python 2.7 would not be affected by this change.

Please comment if dropping support for Python 3.2 and/or Python 3.3 would be a problem for you.

**Comment by hugovk** [comment]
No response == okay to drop support?

+1 for dropping 3.2 and 3.3.

**Comment by PhilippWendler** [comment]
Thanks for your response. As long as I don't get any response that tells me support for these versions is still required I will drop it for BenchExec 2.0, yes.

**Comment by hugovk** [comment]
Sounds sensible. 

By the way, here's the pip installs for benchexec from PyPI for the last year -- no 3.2 or 3.3:

```
$ pypinfo -d 365 --percent --pip benchexec pyversion
python_version percent download_count
-------------- ------- --------------
3.4              52.8%            270
3.5              22.5%            115
2.7              20.7%            106
3.6               3.7%             19
2.6               0.2%              1
```

**Comment by dbeyer** [comment]
I am also in favour of dropping support for old Python versions.
