### ISSUE TITLE
Remove support for executing benchmarks under different user accounts with sudo

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#215]
Since BenchExec 1.3 it is supported to execute benchmarks under different user accounts with sudo. This feature is quite complex and less robust than executing benchmarks without sudo. Furthermore, [container mode](https://github.com/sosy-lab/benchexec/blob/master/doc/container.md) now provides better isolation of runs.

Thus we consider dropping support for this feature in the future. Users should switch to container mode. Please tell us if this is not possible for you and you rely on the sudo feature.

**Comment by dbeyer** [comment]
I support removal.
