### ISSUE TITLE
Do not show differences of timeouts as diff in html-tables.

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#216]
With 0e88e2d42132dfd71b6adcdd1002099824484752 the returncode is part of the status `timeout`. This causes the CPAchecker BuildBot to report many cases of [differences](https://buildbot.sosy-lab.org/results/integration-predicateAnalysis/5776.integration-predicateAnalysis.diff.html), even if the status just switches from `timeout` (without returncode) to `timeout(error 143)` that represents `killed by SIGTERM`.
There are two possibilities:
- either weaken the timeout detection and ignore errorcode `143`
- or weaken the computation of the diff for tables and do not show such differences.

Ideas?

**Comment by PhilippWendler** [comment]
No, nothing needs to be weakened, but if CPAchecker happens to return exit code 143 in case of timeouts (more precisely, if BenchExec sends signal 15 after the soft time limit), this needs to be handled appropriately in CPAchecker's tool-info module. And I have implemented this already in b0a1fe7.

**Comment by kfriedberger** [comment]
Ah, sorry, I had not seen the commit :-)

**Comment by PhilippWendler** [comment]
As an additional note: By selecting some specific value for a column in the "Filter Rows" dialog and then clicking "invert filter", it is possible to hide all rows with this value from the table. This can be used in such a situation where the the diff is too big to look only at the interesting rows.
