### ISSUE TITLE
Distribute run in benchexec

### ISSUE THREAD

**Issue by mchalupa** [sosy-lab/benchexec#232]
Hi,

is there any possibility (even experimental) that can distribute benchexec's run over more machines? I got the feeling that SV-COMP runs are distributed over multiple machines, however, I can't find any option in benchexec, so I wonder whether it was achieved using some external script that runs benchexec, or whether there is some support for distributing runs within benchexec.

Thanks,
Marek

**Comment by PhilippWendler** [comment]
Yes, SV-Comp is executed across multiple machines using the job-distribution system [VerifierCloud](https://vcloud.sosy-lab.org). This system uses BenchExec to ensure technical validity of the results.

BenchExec itself does not have a feature for distributed execution of runs.
(If you have a job distribution system, however, you can implement an integration for BenchExec that lets BenchExec use the existing system to distribute the runs.)

**Comment by mchalupa** [comment]
Thanks!
