### ISSUE TITLE
Investigate use of DataTables library

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#237]
The [DataTables](https://datatables.net/) library seems to be a powerful JavaScript library for tables, providing a lot of features that we have currently implemented ourselves or which would be nice to have:
- [row highlighting](https://datatables.net/examples/api/highlight.html)
- [column hiding](https://datatables.net/examples/api/show_hide.html) with [automatic updating of colspan values](https://datatables.net/examples/advanced_init/complex_header.html)
- [scrolling with fixed header](https://datatables.net/examples/basic_init/scroll_y_dynamic.html)
- [pagination](https://datatables.net/examples/basic_init/alt_pagination.html) with [deferred rendering](https://datatables.net/examples/ajax/defer_render.html) (could be faster for large tables)
- [callbacks for live updating of footer values](https://datatables.net/examples/advanced_init/footer_callback.html) (cf. #125)
- [sorting](https://datatables.net/examples/basic_init/table_sorting.html) including [multi-column sorting](https://datatables.net/examples/basic_init/multi_col_sort.html) (cf. #130)
- [row filters](https://datatables.net/examples/api/multi_filter_select.html)

We should probably use this library in the HTML tables.

**Comment by Nairit11** [comment]
I would like to contribute to this. @PhilippWendler Can you please guide me through this and suggest where should I start from.

**Comment by PhilippWendler** [comment]
Well the goal of this is to investigate if the use of a library like DataTables can make our tables like this [example](https://sosy-lab.github.io/benchexec/example-table/svcomp-simple-cbmc-cpachecker.table.html) render faster (even if the table has 20 columns with 10000 rows) and be more user-friendly. There is a [template](https://github.com/sosy-lab/benchexec/blob/master/benchexec/tablegenerator/template.html) with all the JavaScript code from which these tables are generated. For testing, a somewhat larger table than the example table can be generated by running `bin/table-generator benchexec/tablegenerator/test_integration/results/integration-predicateAnalysis.* -o . --all-columns --no-diff` in the BenchExec project directory.
