### ISSUE TITLE
Additional summary rows for unknown results in table footer

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#239]
In the footer of the HTML tables, there are summary rows for correct and incorrect results, further split into false and true results. We should provide an additional row for unknown results, and a row for each kind of unknown (each value of the status cell that is present in the table). Because this can be many rows, we should make it possible to hide/show them by having tree-style controls with &#8862;/&#8863; symbols.

**Comment by danieldietsch** [comment]
I second that. Also, it seems like there is currently no way of getting a summary if the expected result is unknown. These results should be covered by this summary.

**Comment by PhilippWendler** [comment]
Thanks for your feedback.
The row `Total` in the summary does include unknown (and all other) results of the table, so there is a summary where these are included. Or did I understand your second sentence incorrectly?

**Comment by danieldietsch** [comment]
Yes, but not separately. Have a look at https://monteverdi.informatik.uni-freiburg.de/2017-10-06-result/equality-absintonly-all.2017-10-05_1752.results.AbsInt.html 

For reasons we do not use .prp files in these runs and therefore do not know what the expected result will be. The summary at the end of the table shows no count for true, false, error, etc.

**Comment by PhilippWendler** [comment]
Sure, having a separate row for unknown results is what this issue is about. But I interpreted your comment as saying that unknown results are not included in any summary row.

For an implementation of this feature, however, I have currently other (more important) tasks to implement. But a pull request would certainly be welcome.

**Comment by danieldietsch** [comment]
I do not understand _included_. Unknowns are not included. There is the total row, but that only tells me how many runs were performed.

**Comment by PhilippWendler** [comment]
With *included* I mean what you referred to as *These results should be covered by this summary.*, which I did not understand. The row *Total* shows the same kind of statistics (CPU time etc.) as the other rows, and the measurements of this row do include the unknown results.

**Comment by danieldietsch** [comment]
I see; I did word it rather poorly. I would like to have a separate row for Unknown (i.e. the ones for which there is no expected result), with subrows that contain the actual result of the tool.

**Comment by PhilippWendler** [comment]
The next version of BenchExec will show statistics for the currently visible set of rows according to the defined filters (cf. #125, #616). While this does not exactly provide the functionality requested here, I guess that it is usable in practice for it and provides even more flexibility, so I would tend to close this issue.

**Comment by danieldietsch** [comment]
Yes, I agree. Thank you for the cool new feature!
