### ISSUE TITLE
Use systemd API to create cgroup

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#251]
Currently we create cgroups ourselves, but the kernel is moving in the direction of allowing only a single process to manipulate the cgroup hierarchy. This would be systemd in practice. So we should start migrating to use systemd's dbus API for creating cgroups, and later on for all cgroup accesses.

Documentation on this is available [here](https://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/), we should be able to use a "[scope](https://www.freedesktop.org/software/systemd/man/systemd.scope.html)". We can also look at [systemd-run](https://manpages.debian.org/stretch/systemd/systemd-run.1.en.html) to see how this can be done.

Because scopes can be created by ordinary users, this even has the advantage that in the future we might be able to install and use BenchExec on systems as regular users without any special permissions, which would be great.

**Comment by danieldietsch** [comment]
Would this mean that benchexec then depends on systemd? If so, what about Linux systems without systemd?

**Comment by PhilippWendler** [comment]
No, of course we can simply keep the existing code for systems without systemd.

**Comment by danieldietsch** [comment]
Sounds good, thanks!
