### ISSUE TITLE
TableGenerator: click on 'Quantile Plot' or 'Scatter Plot' does no longer show data at first click

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#260]
Previous behaviour (before latest release 1.11):
Clicking on any of the buttons `Quantile Plot` or `Scatter Plot` showed the data of the column `cputime` (or simply the first available column).

Current behaviour:
After the click there is an empty plot. 
To show `cputime` (or the first availbale column) we must select a different data-column first (like `walltime`), and then switch back to the wanted column.

Wanted:
Revert to previous behaviour!

Might be related to #259 .

**Comment by PhilippWendler** [comment]
Fixing #259 indeed seems to fix this for common tables.

However, I suspect this is still broken if one uses a table-definition XML file that reorders columns.
