### ISSUE TITLE
Use task name in logfile naming and table generation 

### ISSUE THREAD

**Issue by danieldietsch** [sosy-lab/benchexec#263]
We have a scenario where we want to compare the performance of a new analysis on reachability properties as well as memsafety properties. 

For this, we structured our benchmark file in the following way. 
````
<benchmark>
	<rundefinition name="Analysis 1">
		<option name="..." />
		<tasks name="Reach">
			<option name="..." />
			<include>File A</include>
		</tasks>
		<tasks name="Mem">
			<option name="..." />
			<include>File A</include>
		</tasks>
	</rundefinition>
	
	<rundefinition name="Analysis 2">
		<option name="..." />
		<tasks name="Reach">
			<option name="..." />
			<include>File A</include>
		</tasks>
		<tasks name="Mem">
			<option name="..." />
			<include>File A</include>
		</tasks>
	</rundefinition>
</benchmark>
````
When running this benchmark definition, we receive the following warning. 
``WARNING - Input file with name 'File A' appears twice in runset. This could cause problems with equal logfile-names.``

As expected, we only get two logfiles, namely 
 * `Analysis 1.File A.log`
 * `Analysis 2.File A.log`

Obviously, we would like to have all four. 
We also get only one row and two columns in the generated tables, namely a row for ``File A`` and the columns ``Analysis 1`` and ``Analysis 2``. 

It seems like an easy fix for the log file problem would be to add the task name to the log file names and the rows, but any other solution that allows us to 
 * get all four  logfiles 
 * get all four results in the tables generated by ``tablegenerator`` 

would be nice.

**Comment by PhilippWendler** [comment]
This would have the disadvantage that users would have to be careful to always use exactly the same names for their `tasks` tags if they want to create comparison tables. You couldn't create meaningful comparison tables anymore if this name changes (e.g., if you rename a set of tasks).

With a small workaround, you can already achieve what you want:
- Run `benchexec` once for each tasks set using `benchexec -t Mem ...; benchexec -t Reach ...`.
- Use a table definition with the following structure:
```
<union title="Analysis 1">
  <result id="Reach" filename="Analysis 1.*.Reach.xml.bz2"/>
  <result id="Mem" filename="Analysis 1.*.Mem.xml.bz2"/>
</union>
<union title="Analysis 2">
  <result id="Reach" filename="Analysis 2.*.Reach.xml.bz2"/>
  <result id="Mem" filename="Analysis 2.*.Mem.xml.bz2"/>
</union>
```
The `id` attributes in the `result` tags will be used for creating the correct correspondence between tasks.

Furthermore, there is an even better solution: Just add appropriate property files. Then you still need to run the task sets individually, but you can simplify your table definition:
```
<union title="Analysis 1"><result filename="Analysis 1.*.xml.bz2"/></union>
<union title="Analysis 2"><result filename="Analysis 2.*.xml.bz2"/></union>
```
The name of the property will automatically be part of the task id in `table-generator`, such that you do not need the `id` attributes anymore (but you can even combine properties and `id` attributes).

Could you try this out and see if it fits your workflow? If not, we would need a proposal that does not create problems in the use case described above.

**Comment by PhilippWendler** [comment]
It seems the proposed alternatives are sufficient.
