### ISSUE TITLE
Register a Verifier for Attending SV-COMP 2018

### ISSUE THREAD

**Issue by duanzhao-dz** [sosy-lab/benchexec#269]
I want to attend SV-COMP competition 2018,  There is a problem that how to add my Tool-Info Module to https://github.com/sosy-lab/benchexec/tree/master/benchexec/tools

**Comment by kfriedberger** [comment]
You have to create a pull request for your tool module.
Please fork the repository, apply your changes in your fork, then create a pull request on GitHub.
