### ISSUE TITLE
link to source file in html points to wrong directory.

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#271]
I have several tables, where the relativ URL to source file points to a wrong sourcefile.

I have benchmark-definitions at `test/test-sets/` results and tables at `test/results/` and source files at `test/programs/benchmarks/`. The generated html table contains links of the following structure: `href="../../../programs/benchmarks/` which is two directory levels too high and does not find the source file.

**Comment by PhilippWendler** [comment]
For all bug reports, please state which version you are using.

Did you move any files manually between benchmark execution and looking at the table?
Which command-line options did you pass to `benchexec` and `table-generator`?

**Comment by kfriedberger** [comment]
I use `benchexec 1.12` as integrated into current CPAchecker.
- `scripts/benchmark.py test/test-sets/integration-concurrency.xml --cloud`.
- `scripts/table-generator.py 'test/results/integration-concurrency.2017-10-24_0825.results.xml.bz2'`
The filename in the result-XML-file is, for example, 
`../programs/benchmarks/pthread-wmm/mix000_pso.opt_false-unreach-call.i` 
and the corresponding link in the HTML-table is 
`../../../programs/benchmarks/pthread-wmm/mix000_pso.opt_false-unreach-call.i`.
Note that in my case `cpachecker/test/programs/benchmarks` is a symlink to `../../../sv-benchmarks/c`,
i.e., the CPAchecker-directory is a sibling of the sv-benchmark.

**Comment by PhilippWendler** [comment]
Could you please test this?
