### ISSUE TITLE
Data about system set to unknown when aborting a benchmark. 

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#284]
I do not know whether this issue should be reported for VCloud or for BenchExec.

When I abort a long running benchmark that is executed via VCloud and generate a table (from the partial results), the data about host, system, and os is missing and reported as `unknown`. Could we use the available data from the finished runs?

**Comment by PhilippWendler** [comment]
The VCloud outputs this information only after all runs are received, BenchExec cannot do anything here.
