### ISSUE TITLE
cgroups problem with Docker Community Edition

### ISSUE THREAD

**Issue by inkytonik** [sosy-lab/benchexec#289]
OS Mac OS 10.13.3
Benchexec 1.16
Docker Version 17.12.0-ce-mac49 (21995)

We've previously used Docker and benchexec together to run SV-COMP-based experiments. Unfortunately, since Docker moved to the Community Edition our previous configuration doesn't work any more.

The symptom is that the cgroups setup that we were using isn't working. We followed the benchexec instructions and start docker as follows:

    docker run -v /sys/fs/cgroup:/sys/fs/cgroup:rw ...

This was all working fine with a previous version of Docker, but now benchexec doesn't work. We get the following error when we check the cgroups config:

    # python3 -m benchexec.check_cgroups
    WARNING: Cannot use cgroup hierarchy mounted at /sys/fs/cgroup/cpuacct/docker-ce/docker/17e94e79eb73327818b28b6b09f01e9e86b1615e914dcf922c884df8c3cab59e for subsystem cpuacct, reason: No such file or directory. If permissions are wrong, please run "sudo chmod o+wt '/sys/fs/cgroup/cpuacct/docker-ce/docker/17e94e79eb73327818b28b6b09f01e9e86b1615e914dcf922c884df8c3cab59e'".
    WARNING: Without cpuacct cgroups, cputime measurement and limit might not work correctly if subprocesses are started.
    WARNING: Cannot use cgroup hierarchy mounted at /sys/fs/cgroup/freezer/docker-ce/docker/17e94e79eb73327818b28b6b09f01e9e86b1615e914dcf922c884df8c3cab59e for subsystem freezer, reason: No such file or directory. If permissions are wrong, please run "sudo chmod o+wt '/sys/fs/cgroup/freezer/docker-ce/docker/17e94e79eb73327818b28b6b09f01e9e86b1615e914dcf922c884df8c3cab59e'".
    WARNING: Cannot reliably kill sub-processes without freezer cgroup.
    WARNING: Cannot use cgroup hierarchy mounted at /sys/fs/cgroup/memory/docker-ce/docker/17e94e79eb73327818b28b6b09f01e9e86b1615e914dcf922c884df8c3cab59e for subsystem memory, reason: No such file or directory. If permissions are wrong, please run "sudo chmod o+wt '/sys/fs/cgroup/memory/docker-ce/docker/17e94e79eb73327818b28b6b09f01e9e86b1615e914dcf922c884df8c3cab59e'".
    WARNING: Cannot measure memory consumption without memory cgroup.
    WARNING: Cannot use cgroup hierarchy mounted at /sys/fs/cgroup/cpuset/docker-ce/docker/17e94e79eb73327818b28b6b09f01e9e86b1615e914dcf922c884df8c3cab59e for subsystem cpuset, reason: No such file or directory. If permissions are wrong, please run "sudo chmod o+wt '/sys/fs/cgroup/cpuset/docker-ce/docker/17e94e79eb73327818b28b6b09f01e9e86b1615e914dcf922c884df8c3cab59e'".

Notice that the path names include "docker-ce" which I don't think was present before.

Does anyone have any advice that will help us resolve the problem?

**Comment by PhilippWendler** [comment]
Hm, I have a suspicion. Do you know whether your Docker now uses a [cgroup namespace](http://man7.org/linux/man-pages/man7/cgroup_namespaces.7.html)? Maybe this is mentioned somewhere in the release notes of your new version?

In principle, cgroup namespaces will improve the situation of nested containers (e.g., BenchExec inside Docker), but I am not sure whether BenchExec needs to be changed. Probably at least the `-v /sys/fs/cgroup:/sys/fs/cgroup:rw` will break cgroup namespaces.

So could you please try Docker without this parameter? Does Docker now have a parameter for enabling nested cgroups? If yes, please enable it.

If this does not work, we should start some manual investigation. Can you please check inside your Docker container what files/directories are present in `/sys/fs/cgroup` and `/sys/fs/cgroup/cpuacct`? Please also post the output of `cat /proc/self/cgroup` inside the Docker container.

**Comment by inkytonik** [comment]
Thanks Philipp. It seems that this may well be the problem. I haven't been able to identify an "enable nested cgroup" option for Docker but there are many options and I am far from an expert :-)

Running without the -v option didn't help.  Here are the results of poking around:

    # cat /proc/self/cgroup
    13:name=systemd:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    12:pids:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    11:hugetlb:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    10:net_prio:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    9:perf_event:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    8:net_cls:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    7:freezer:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    6:devices:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    5:memory:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    4:blkio:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    3:cpuacct:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    2:cpu:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd
    1:cpuset:/docker-ce/docker/4b594f13acb2c123e3c8edf34f96ec62db02f7f57812af2b376fb56c258709bd

    # ls /sys/fs/cgroup
    blkio/  cpu/  cpuacct/  cpuset/  devices/  freezer/  hugetlb/  memory/  net_cls/  net_prio/  perf_event/  pids/  systemd/

    # ls /sys/fs/cgroup/cpuacct
    cgroup.clone_children  cpuacct.stat   cpuacct.usage_all     cpuacct.usage_percpu_sys   cpuacct.usage_sys   notify_on_release
    cgroup.procs           cpuacct.usage  cpuacct.usage_percpu  cpuacct.usage_percpu_user  cpuacct.usage_user  tasks

**Comment by PhilippWendler** [comment]
Interesting, this indicates a problem that is the opposite of my suspicion: `/proc/self/cgroup` is as expected *without* cgroup namespaces, but the content of the cgroup directories does not match (it is such that it would work correctly only with cgroup namespaces). It seems that your new Docker always mounts something to `/sys/fs/cgroup/cpuacct`, which it previously did not. (Just for confirmation, you could post the output of `findmnt` in the container.)

You can try the following alternatives:
1. Enable cgroup namespaces in your Docker (however, I do not know whether this is supported, and what kernel version you need).
1. Replace the parameter with `-v /sys/fs/cgroup:/sys/fs/cgroup-root:rw`: This will add an additional cgroup mount. BenchExec should pick it up automatically, if not, we can fix that within BenchExec.
2. Add one such parameter for each of the sub-directories `blkio`, `cpuacct`, `cpuset`, `freezer`, and `memory`, e.g., `-v /sys/fs/cgroup/cpuacct:/sys/fs/cgroup/cpuacct:rw` and similarly for the others.
3. Find some switch in Docker that disables this new behavior (could be described as "disable cgroup access in container") and continue to use the existing parameter.

**Comment by inkytonik** [comment]
Ok, thanks. Will try these alternatives. For the record, here is the output of `findmnt`:

    root@b84a3edf7712:/skink# findmnt
    TARGET                          SOURCE                                                                                       FSTYPE     OPTIONS
    /                               none                                                                                         aufs       rw,relatime,si=bb2e6c9b0dcf9962,dio,dirperm1
    |-/proc                         proc                                                                                         proc       rw,nosuid,nodev,noexec,relatime
    | |-/proc/bus                   proc[/bus]                                                                                   proc       ro,relatime
    | |-/proc/fs                    proc[/fs]                                                                                    proc       ro,relatime
    | |-/proc/irq                   proc[/irq]                                                                                   proc       ro,relatime
    | |-/proc/sys                   proc[/sys]                                                                                   proc       ro,relatime
    | |-/proc/sysrq-trigger         proc[/sysrq-trigger]                                                                         proc       ro,relatime
    | |-/proc/kcore                 tmpfs[/null]                                                                                 tmpfs      rw,nosuid,size=65536k,mode=755
    | |-/proc/timer_list            tmpfs[/null]                                                                                 tmpfs      rw,nosuid,size=65536k,mode=755
    | |-/proc/sched_debug           tmpfs[/null]                                                                                 tmpfs      rw,nosuid,size=65536k,mode=755
    | `-/proc/scsi                  tmpfs                                                                                        tmpfs      ro,relatime
    |-/dev                          tmpfs                                                                                        tmpfs      rw,nosuid,size=65536k,mode=755
    | |-/dev/console                devpts[/0]                                                                                   devpts     rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=
    | |-/dev/pts                    devpts                                                                                       devpts     rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=
    | |-/dev/mqueue                 mqueue                                                                                       mqueue     rw,nosuid,nodev,noexec,relatime
    | `-/dev/shm                    shm                                                                                          tmpfs      rw,nosuid,nodev,noexec,relatime,size=65536k
    |-/sys                          sysfs                                                                                        sysfs      ro,nosuid,nodev,noexec,relatime
    | |-/sys/firmware               tmpfs                                                                                        tmpfs      ro,relatime
    | `-/sys/fs/cgroup              tmpfs                                                                                        tmpfs      ro,nosuid,nodev,noexec,relatime,mode=755
    |   |-/sys/fs/cgroup/cpuset     cpuset[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]   cgroup     ro,nosuid,nodev,noexec,relatime,cpuset
    |   |-/sys/fs/cgroup/cpu        cpu[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]      cgroup     ro,nosuid,nodev,noexec,relatime,cpu
    |   |-/sys/fs/cgroup/cpuacct    cpuacct[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]  cgroup     ro,nosuid,nodev,noexec,relatime,cpuacct
    |   |-/sys/fs/cgroup/blkio      blkio[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]    cgroup     ro,nosuid,nodev,noexec,relatime,blkio
    |   |-/sys/fs/cgroup/memory     memory[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]   cgroup     ro,nosuid,nodev,noexec,relatime,memory
    |   |-/sys/fs/cgroup/devices    devices[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]  cgroup     ro,nosuid,nodev,noexec,relatime,devices
    |   |-/sys/fs/cgroup/freezer    freezer[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]  cgroup     ro,nosuid,nodev,noexec,relatime,freezer
    |   |-/sys/fs/cgroup/net_cls    net_cls[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]  cgroup     ro,nosuid,nodev,noexec,relatime,net_cls
    |   |-/sys/fs/cgroup/perf_event perf_event[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]
    |   |                                                                                                                        cgroup     ro,nosuid,nodev,noexec,relatime,perf_event
    |   |-/sys/fs/cgroup/net_prio   net_prio[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3] cgroup     ro,nosuid,nodev,noexec,relatime,net_prio
    |   |-/sys/fs/cgroup/hugetlb    hugetlb[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]  cgroup     ro,nosuid,nodev,noexec,relatime,hugetlb
    |   |-/sys/fs/cgroup/pids       pids[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]     cgroup     ro,nosuid,nodev,noexec,relatime,pids
    |   `-/sys/fs/cgroup/systemd    cgroup[/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3]   cgroup     ro,nosuid,nodev,noexec,relatime,name=systemd
    |-/skink                        osxfs[/asloane/Desktop/Skinky/skink]                                                         fuse.osxfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allo
    |-/etc/resolv.conf              /dev/sda2[/docker/containers/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3/resolv.conf]
    |                                                                                                                            ext4       rw,relatime,data=ordered
    |-/etc/hostname                 /dev/sda2[/docker/containers/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3/hostname]
    |                                                                                                                            ext4       rw,relatime,data=ordered
    `-/etc/hosts                    /dev/sda2[/docker/containers/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3/hosts]
                                                                                                                                 ext4       rw,relatime,data=ordered

**Comment by inkytonik** [comment]
Alternative #2: running with `-v /sys/fs/cgroup:/sys/fs/cgroup-root:rw` gives an error about a read-only file system.

    docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/sys/fs/cgroup\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/baa4f8c51df08e3803c1927ae9b5f449d74cfe9b6558171032667ef0c2e54122\\\" at \\\"/var/lib/docker/aufs/mnt/baa4f8c51df08e3803c1927ae9b5f449d74cfe9b6558171032667ef0c2e54122/sys/fs/cgroup-root\\\" caused \\\"mkdir /var/lib/docker/aufs/mnt/baa4f8c51df08e3803c1927ae9b5f449d74cfe9b6558171032667ef0c2e54122/sys/fs/cgroup-root: read-only file system\\\"\"": unknown.

Alternative #3: doesn't give an error but bench exec is still not happy. I tried 

    -v /sys/fs/cgroup/cpuacct:/sys/fs/cgroup/cpuacct:rw -v /sys/fs/cgroup/freezer:/sys/fs/cgroup/freezer:rw -v /sys/fs/cgroup/memory:/sys/fs/cgroup/memory:rw -v /sys/fs/cgroup/cpuset:/sys/fs/cgroup/cpuset:rw

`findmnt` reports mounts like this:

    |   |-/sys/fs/cgroup/cpuacct    cpuacct[/docker-ce/docker/3d2ef090076f107a6cb79fa503d91e10446a617507e8cabe594b5b1869669607]
    |   |                                                                                                cgroup     ro,nosuid,nodev,noexec,relatime,cpuacct
    |   | `-/sys/fs/cgroup/cpuacct  cpuacct[/docker-ce]                                                  cgroup     rw,nosuid,nodev,noexec,relatime,cpuacct

**Comment by PhilippWendler** [comment]
The `findmnt` output confirms my suspicion. Dockers mounts the `/docker-ce/docker/b84a3edf7712489162294c59e8b191b4d727283741dc1d1515eee256500bc9c3` cgroup as the root cgroup in the container. This is desired from a point of view of a container framework, but incorrect without cgroup namespaces, because `/proc/self/cgroup` still contains the full cgroup name.

Alternative 3 seems to have the problem that there is still not the root cgroup which is mounted in the container, but the `/docker-ce` cgroup. I have no idea why this happens. Maybe the process that handles the mounts already lives inside a container that has `/docker-ce` as the root cgroup?

For Alternative 2 to work, one would probably need to make `/sys/fs/` in the container writable. Maybe it its easier to mount them somewhere else. You could try `-v /sys/fs/cgroup:/tmp/cgroup:rw`. However, it could happen that the same problem as with Alternative 3 occurs (please check with `findmnt`).

To circumvent the problem from Alternative 3, one could try the following:
Outside of Docker, create a bind mount of `/sys/fs/cgroup` to somewhere else, like `/tmp/cgroup`. Then run Docker with `-v /tmp/cgroup/cpuacct:/sys/fs/cgroup/cpuaact`.

Another attempt could be to go to `/sys/fs/cgroup/cpuacct` in the container and create a symlink with name `docker-ce` that points to `.` (such that in the end, `/sys/fs/cgroup/cpuacct/docker-ce` points to `/sys/fs/cgroup/cpuacct`. After that, BenchExec should work (if done for all of the cgroup hierarchies that BenchExec needs). If you find a way to figure out the container id automatically, you could use this symlink trick for `docker-ce/docker/<ID>` and keep the original `-v` parameter.

Note that the correct solution for this all this would be the use of cgroup namespaces by Docker, everything else are just workarounds for the inconsistent containers that Docker creates for you.

**Comment by inkytonik** [comment]
I've been unable to resolve this problem so far. I'd like to use a "correct" solution but everything I've tried (e.g., setting the cgroup_parent argument when running Docker) has not fixed things. 

I posted a question on the Docker community forum. Hopefully someone there can help.

https://forums.docker.com/t/cgroup-problem-with-docker-ce-and-ubuntu/47413

**Comment by inkytonik** [comment]
It seems that just waiting has fixed this one. The latest Docker for Mac version:

    Version 18.03.0-ce-mac60 (23751)

and benchexcec get along as we had previously seen with older Docker versions. We are using the recommended 

    -v /sys/fs/cgroup:/sys/fs/cgroup:rw

setup as before.
