### ISSUE TITLE
"nan" as a column value crashes table-generator

### ISSUE THREAD

**Issue by mdangl** [sosy-lab/benchexec#302]
My understanding is that
1. any string is supposed to be a valid value of the ```value``` attribute of the ```column``` tag within a ```run``` tag in a result file and
2. there is some special magic that computes interesting statistics (sum, min, max, average, median, ...) for columns where the values are numbers.

However, if I put the string "nan" as a column value (but not for any other non-numeric string!), the table generator crashes:
```ValueError: cannot convert float NaN to integer at line 252 column 82```
I attached an [example XML file](https://github.com/sosy-lab/benchexec/files/2180602/nan-error.xml.zip) that triggers the error.

I presume the reason is that one part of the code tries to graciously interpret "nan" (in any capitalization) as the floating point (non-)value ```NaN```, while another part is not able to handle it.
Of course, this raises the question *how* to handle ```NaN```. Two options would be:
1. treat it like any other non-numeric string
2. use ```NaN``` logic for the summary rows, i.e. any column with at least one ```NaN``` would produce a ```NaN``` summary (sum, min, max, average, median, ...).

For what it's worth, in *my* case the ```NaN``` was a bug in my benchmarks, so I had to fix it on my end anyway, but in the general case, I would not expect ```NaN```s to crash the table generator.

**Comment by leostrakosch** [comment]
I'm currently prefering the second option, i.e., handling `NaN` as the float value `NaN`.
If we interpret `NaN` as a string, all values in that column will be interpreted as a string and we will lose
proper formatting.
In addition, handling the float value `NaN` as a float is closer to its real semantics than handling it as a string.

**Comment by leostrakosch** [comment]
Oh, and your understanding is correct.

> My understanding is that
> 1. any string is supposed to be a valid value of the value attribute of the column tag within a run tag in a result file and
> 2. there is some special magic that computes interesting statistics (sum, min, max, average, median, ...) for columns where the values are numbers.

Regarding 2., interesting statistics are **only** computed if all values of that column can be identified as numbers (unless this has changed).

**Comment by PhilippWendler** [comment]
The first bug to fix is: Why does `Column.format_value` attempt to format values in text columns? I am actually surprised to see that this method does not check the column type, and I am also surprised to see that it actually seems to return the correct value for text columns (i.e., without rounding). @leostrakosch Do you know why this works?

Afterwards we can add support for treating `Nan` as a number, I already know how this could be done.

**Comment by leostrakosch** [comment]
I think it jumped into the correct branch because of a lucky choice of if-else conditions:
https://github.com/sosy-lab/benchexec/blob/f162c2d14ef486c7f68b78302897f15f0d444c1b/benchexec/tablegenerator/columns.py#L187-L193

I've created a PR to fetch non-number fields early.

**Comment by leostrakosch** [comment]
... and for non-number values, it ran into the
catch-block:

https://github.com/sosy-lab/benchexec/blob/f162c2d14ef486c7f68b78302897f15f0d444c1b/benchexec/tablegenerator/columns.py#L168-L171
