### ISSUE TITLE
Saving Runs with Benchexec

### ISSUE THREAD

**Issue by animeshbchowdhury** [sosy-lab/benchexec#305]
Hi,

I wanted to know the flags/commands with which, I can dump all files and folders generated by the tool corresponding to each run. Right now, the option is given to dump a file/set of files, in the logfiles, using <resultfile>.

Regards,
Animesh

**Comment by PhilippWendler** [comment]
Sorry, I do not fully understand your question.

In principle, `<resultfiles>` is the tag with which you can select the files that you want, but the default is to select all files anyway. This is explained [here](https://github.com/sosy-lab/benchexec/blob/2c98ac735ab018e890419b2e2a8b5a9220bcdcec/doc/container.md#retrieving-result-files). Note that it only works if you specify [`--container`](https://github.com/sosy-lab/benchexec/blob/master/doc/container.md).

Is there anything that is left unclear by the documentation?

**Comment by animeshbchowdhury** [comment]
I referred this documentation only. I didn't use the flag - - container with benchexec.
Thanks for the help. It is working now. 

Best Regards, 
Animesh

**Comment by animeshbchowdhury** [comment]
I referred this documentation only. I didn't use the flag - - container with benchexec.
Thanks for the help. It is working now. 

Best Regards, 
Animesh
