### ISSUE TITLE
'runexec --container' fails if a docker container is running 

### ISSUE THREAD

**Issue by MateusAraujoBorges** [sosy-lab/benchexec#314]
_All tests performed on Ubuntu 18.04 64-bit with benchexec a41f0cb8 and the latest docker-ce package  ('18.06.1\~ce\~3-0\~ubuntu')._

Hello,

I'm having trouble running benchexec/runexec while other docker containers are running in the same machine. Please look at the logs below:

_Without any docker containers running:_
```
(benchexec) mateus@alearis:~/workspace/benchexec$ runexec --container -- ls
2018-09-13 15:22:48,114 - WARNING - Kernel misses feature for accounting swap memory, but machine has swap. Memory usage may be measured inaccurately. Please set swapaccount=1 on your kernel command line or disable swap with "sudo swapoff -a".
2018-09-13 15:22:48,115 - INFO - Starting command ls
2018-09-13 15:22:48,115 - INFO - Writing output to output.log
[...] 
```

_While `docker run -it ubuntu bash` runs in another terminal_
```
(benchexec) mateus@alearis:~/workspace/benchexec$ runexec --container -- ls                      
2018-09-13 15:18:45,465 - WARNING - Kernel misses feature for accounting swap memory, but machine has swap. Memory usage may be measured inaccurately. Please set swapaccount=1 on your kernel command line or disable swap with "sudo swapoff -a".
2018-09-13 15:18:45,466 - INFO - Starting command ls
2018-09-13 15:18:45,466 - INFO - Writing output to output.log
2018-09-13 15:18:45,483 - CRITICAL - Failed to configure container: [Errno 13] Creating overlay mount for '/var/lib/docker/overlay2/fbc65ec970acff825a62ae802b8fc96c247109cdeb5bd6ca973954685a324ec9/merged' failed: Permission denied. Please use other directory modes.
2018-09-13 15:18:45,638 - CRITICAL - Cannot execute 'ls': execution in container failed, check log for details.
[...]
```

The folder reported in the critical log message is the overlayfs mount used by the docker container. I'm not familiar with the intricacies of overlayfs/containers/etc., but it seems quite strange to me that runexec is trying to mount over an existing (and unrelated) directory instead of creating a new one.

--
Mateus

**Comment by PhilippWendler** [comment]
Thanks for reporting this.

BenchExec creates a container in which all the filesystems that are visible on the host are visible, but mounts an overlayfs on top of each of them, and this seems to fail for those filesystems from a Docker container (which is not really surprising).

I guess you do not want to have the Docker filesystems visible in the BenchExec container, so you could start runexec with `--hidden-dir /var/lib/docker` and it should work.

I would also like to change BenchExec to do the right thing automatically in this situation, but would need to have a little bit more info. Could you please post the output of `mount | grep docker` while such a container is running?
Could you please also check whether your user account has permissions to view the directory from the error message, or is there some (parent) directory which is inaccessible for your user?

**Comment by MateusAraujoBorges** [comment]
Hi Philipp,

Thanks for the quick response. Here's the output of `mount | grep docker`:

```
(benchexec) mateus@alearis:~$ mount | grep docker                                                                                                                                                                                                                                         
overlay on /var/lib/docker/overlay2/baef2d18e94ba7a6c95f43b01c888888a7e9fcbce8e1db580c4df2c792f11d4c/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/7EINCX2FS37FJ6FXSURHHIAJK5:/var/lib/docker/overlay2/l/G7OZCGQ5I4BQMJRDZGDS7TRHLH:/var/lib/docker/overlay2/l/37WP6LTSCW6LP26G63CL46VHZQ:/var/lib/docker/overlay2/l/QIEQMZCC6CO4WSF7SZPBTBJPGP:/var/lib/docker/overlay2/l/7TJWNYE462OPEZANONUCN72UDD:/var/lib/docker/overlay2/l/QIQS4HI4WVWXYWOI6L22WMBYPG,upperdir=/var/lib/docker/overlay2/baef2d18e94ba7a6c95f43b01c888888a7e9fcbce8e1db580c4df2c792f11d4c/diff,workdir=/var/lib/docker/overlay2/baef2d18e94ba7a6c95f43b01c888888a7e9fcbce8e1db580c4df2c792f11d4c/work)                                                                                                                                                                          
shm on /var/lib/docker/containers/d5631fc91cc7c2da22923272f372b4422e2af082ab40e8fb7bd3a7b18c1c72da/mounts/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)                                                                                                                    
nsfs on /run/docker/netns/2aa3de5dcce4 type nsfs (rw)                                                                                                                                                                                                                                     
```

Furthermore, my account doesn't has permissions to view the contents of `/var/lib/docker`.

**Comment by PhilippWendler** [comment]
Thanks. I guess I will change BenchExec to automatically assume `--hidden-dir` for directories with mount points that are no accessible to the current user.
