### ISSUE TITLE
javac.py does not find .java source files

### ISSUE THREAD

**Issue by peterschrammel** [sosy-lab/benchexec#334]
At https://github.com/sosy-lab/benchexec/blob/master/benchexec/tools/javac.py#L41
the `tasks` variable contains the benchmark's `.yml` file, whereas `get_files` expects a list of paths. It seems that parsing the `.yml` file to extract the `input_files` is missing.

**Comment by PhilippWendler** [comment]
If you use `.yml` files, you need to use the `yaml` branch of BenchExec until it is merged.
