### ISSUE TITLE
CI tests for tool-info modules

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#344]
Getting tool-info modules right seems to be the most difficult part in using BenchExec.
Therefore, we need to make it more convenient for users to test the tool-info modules.

Issue #343 suggests to give an example binary archive of a tool that is to be benchmarked with BenchExec.

So a CI could run as follows:
```
for each tool-info module <tool>.py:
    if archive is provided in annotation in <tool>.py
        download the archive, unzip on success
        run the test of the tool-info module (using the binaries)
```

**Comment by PhilippWendler** [comment]
For this we don't even need #343. In a CI script we can just hard-code the SV-COMP repo(s) and attempt to load tools from there.

However, the benefit we get might be smaller than we hope. The most crucial changes to the tool-info modules are those done in the beginning of each year's SV-COMP period, when the verifier archive is often not yet merged and would not be available for CI.

But it is still worth doing this, even if only for ensuring backwards-compatibility of the tool-info module with previous versions of the verifier.

**Comment by dbeyer** [comment]
Believe me, the benefit would be extremely large!  I am still fixing tool-info modules where some components are not found.

**Comment by dbeyer** [comment]
Tests we need (just to get started with a list):
* executable file available
* executable file has execution permission
* all files with execution permission are included in the REQUIRED_PATHS
* version string not empty

**Comment by PhilippWendler** [comment]
Ok, but these kinds of tests would need to be put into the CI of the archives repo, not into CI for BenchExec. After all, you need to run these tests whenever the archive gets updated.

In BenchExec, we would test things like bad code in the tool-info module.

**Comment by dbeyer** [comment]
Yes, right.
But the last two are tests of the tool-info module and require that code to be fixed.

**Comment by PhilippWendler** [comment]
The above mentioned tests are specific to requirements of SV-COMP and Test-Comp. Furthermore, in competition scenarios the tool archives are available, whereas in general for other tool-info modules they are not. So I think this is all better handled in the respective competition's tool chains, e.g., the CI of the relevant repositories.
