### ISSUE TITLE
Functions pre-process and post-process for tool execution

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#349]
There are use cases for which it is necessary to prepare something before running a tool,
and to process some output files after the tool (was) terminated.

post-processing: Currently this needs to be done in the function `determine_result`,
but the name and design suggests that this function is meant for post-processing
of the log output in order to determine the uniform representation of the result of the run.

pre-processing: Currently, this could be done in the function `executable`,
but this is even more of an ugly hack than the current way of doing post-processing.

Is it a good idea to introduce two functions `pre-process` and `post-process`,
with the semantics that BenchExec executes `pre-process` before, and `post-process` after,
the run with `runexec`?

**Comment by PhilippWendler** [comment]
What would be examples for such functions? Shouldn't such things be done inside the run?

**Comment by dbeyer** [comment]
Ideally yes. But not always.
I intend to use BenchExec to run TestComp.
There, for the first edition of that competition, a preprocessing step for the C programs is necessary.
Also, for the postprocessing, the output of the test-case generators is to be uniformized.

A goal of most competitions is to establish standards, and after the first edition,
there will be a rule-convention to make the preprocessing step unnecessary and
an exchange format to make the postprocessing unnecessary.

**Comment by dbeyer** [comment]
> Is this a preprocessing step per task or globally?

Per task.

> Is this preprocessing specific per tool?

Specific per tool.

> Who should define the preprocessing? The author of the tool-info module or the author of the benchmark definition?

Author of tool-info module.

> Does the preprocessing need to be executed in a container?

Ideally, yes, for sure for security reasons.

> This seems to be quite complex and difficult to get right.

I agree.

> For example, if we do not execute the preprocessing in a container, it would probably change locally existing files. Thus, running the preprocessing again (in a second benchmark run) could fail because of the already preprocessed files.

Would need to be in a container.

> I doubt that this feature is worth the effort and the complexity compared to the two existing alternatives:

I agree. (And close the issue.)
