### ISSUE TITLE
header in local HTML-table without loading local Javascript not scrolling scroll left-right.

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#375]
I know this case is weird, but I got a html-table for some tool via mail and opening it is not nice.
The table was created in local mode (or maybe downloaded from sosy-lab-server including all Javascript sources), such that all internal references to Javascript files are pointing to local files, which were not part of the mail :-(

When opening this local html-table, no Javascript-files are available and some features are missing. I am ok with that, because at least the table is readable.
However, all Javascript-related buttons are shown (and useless) and the header is floating (yes, that works partially). My problem is that the header does not move from riht to left when scrolling from left to right in larger tables. I can not read the right half of the header.

The wanted solution is 
- (important for me:) to deactivate the floating header if some important Javascript files are missing, and
- (important for users in general:) to deactivate all buttons if Javascript cannot be loaded.

**Comment by PhilippWendler** [comment]
The second is implemented since these buttons exist.
