### ISSUE TITLE
Use container mode in tool-info module for version information

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#384]
Many tool-info modules execute the tool to get the version number. In order to prevent the tool from (accidentally) modifying files, this execution should happen in a container, just like the actual run execution.

**Comment by PhilippWendler** [comment]
A tricky part of this is that of course container mode should be used only if it is also active for the actual runs, but the configuration that contains this information is not available to the tool-info module.

**Comment by dbeyer** [comment]
Related to issue #173.

**Comment by PhilippWendler** [comment]
Actually not related. #173 is about a cgroup, which is completely independent from the container mode, and would not be implemented in a similar manner.

**Comment by dbeyer** [comment]
> A tricky part of this is that of course container mode should be used only if it is also active for the actual runs, but the configuration that contains this information is not available to the tool-info module.

Why?  I would say that independently from how `runexec` starts the tool, `benchexec` itself should be executed as safely and securely as possible.

**Comment by PhilippWendler** [comment]
Container mode is not possible on all systems. So if the user passes `--no-container`, we must not use the container mode, neither for the actual runs nor for getting the version information.

**Comment by dbeyer** [comment]
> Actually not related. #173 is about a cgroup, which is completely independent from the container mode, and would not be implemented in a similar manner.

The abstract idea is very related ;-) and my comment in that issue #173 was actually referring to this aspect already, as I interpreted the title of the issue a bit more widely. I will drop a comment there.

**Comment by dbeyer** [comment]
> Container mode is not possible on all systems.

I know. But `benchexec` can find out itself.

> So if the user passes `--no-container`, we must not use the container mode, neither for the actual runs nor for getting the version information.

Not necessarily.  I would interpret the option `--no-container` as relating to how the process invocation happens for the experiment execution, by `runexec`.  For the `benchexec` execution, I would simply assume that it is executed as securely as possible.

In other words, just from the user perspective, if name spaces are available, I would expect `benchexec` to execute itself in a new name space, and if name spaces are not available, I would expect it to print a warning that (a) files are not guaranteed to stay valid and (b) the tool is executed with a full view of the host system.

... just my immediate thoughts from SV-COMP execution experience.

**Comment by kfriedberger** [comment]
What about the following solution:
If container-mode is wanted and available, then use it for the version-info.
Otherwise check whether any file or directory that would be sent into the VerifierCloud was modified and warn the user about it. 
For the second case, a simple list of files from all to-be-sent-directories with their hashes might be sufficient.

**Comment by PhilippWendler** [comment]
> > Container mode is not possible on all systems.
> 
> I know. But `benchexec` can find out itself.

No. Attempting to use a container on a system where not everything necessary is available can lead to all sorts of different errors. Attempting to differentiate this from other possible errors when executing a tool (binary not present, binary not executable, etc.) would be too error-prone.

**Comment by dbeyer** [comment]
This issue really describes a bunch of problems that BenchExec currently has:
- Security (object system can observe host system without sufficient protection)
- Multi-threading (ability of the object system to change itself can cause race conditions)
- Replicability (experiments might not be replicable, because the object system might be changed with every call of `benchexec`)
  The benchmark should be started on an "untouched" copy of the object system.
