### ISSUE TITLE
How to allow properties unknown to Benchexec?

### ISSUE THREAD

**Issue by lembergerth** [sosy-lab/benchexec#386]
I'm trying to use benchexec with a property that is apparently not known to it.

It fails with the following message:
`File "../sv-benchmarks/c/properties/coverage-branches.prp" does not contain a known property.`

Ignoring the orthogonal question whether BenchExec should get to know these properties (which is also not important to me), my question is the following:

**Is there any way to run BenchExec with a property unknown to it?**

The reason behind this:
I specify my property in the `<propertyfile>`-tag of my benchmark definition not to tell BenchExec about it,
but because I want my tool to use that property, and the `<propertyfile>` tag is IMO a more elegant way than providing a tool-specific command-line parameter, because I can rely on the tool-info module to flip the right switches.

In addition, it may be the case that I want to use some other tool that supports, thanks to its tool-info module, that property when given as a `<propertyfile>`, but that doesn't even have any command-line switches to do so. In that case, I am, at the moment, not able to provide the specification at all.

**Comment by PhilippWendler** [comment]
> **Is there any way to run BenchExec with a property unknown to it?**

Yes, since version 1.17. You need to declare the task in a [task-definition file](https://github.com/sosy-lab/benchexec/blob/27f20014c1c4a7d0199317f0964991a0110d6225/doc/benchexec.md#task-definition-files).

**Comment by lembergerth** [comment]
Thanks for the quick reply!

If I provide a task-definition file with multiple properties and I only want to take the benchmark tasks of a certain property that is unknown to benchexec,
is it possible to provide a `<propertyfile>` tag in the benchmark definition to do so, even though this property is not known to benchexec?
Or do I have to write a task-definition file that only contains that unknown property, then?

**Comment by PhilippWendler** [comment]
Yes, this is possible. In fact, you need to specify `<propertyfile>` in the benchmrak definition, otherwise property files won't get used at all.

**Comment by lembergerth** [comment]
D'oh, makes sense.
Thanks for the help! :-)
