### ISSUE TITLE
YAML task definition: Confusing semantics of variable 'inputfile_name'

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#390]
In the following, 'variable' refers to variables that can be used in the table-definition files for the table generator.

Variable `inputfile_name` was previously holding the name of the file that is given as input to the tool to benchmark. When using YAML task definitions, variable `inputfile_name` holds the name of the task-definition file (.yml file).

Possible solution: Introduce variable `taskdef_name` to hold the name of the .yml file,
and have `inputfile_name` hold the "real" input file again.

**Comment by PhilippWendler** [comment]
There is no "real" input file anymore, because input files are now just a list of paths.

So we can add `taskdef_name`, but it would only be an alias for `inputfile_name`.

**Comment by dbeyer** [comment]
For inspecting results using BenchExec's HTML tables, it was convenient that the benchmarking engineer could click on an entry in the table to open the input file.  Any idea on how to achieve this?

`first_inputfile_name` perhaps?

Or, even more complete, offer a set or sequence:
`inputfile_set` perhaps?

**Comment by dbeyer** [comment]
> it would only be an alias for `inputfile_name`

Disadvantage: This is semantically wrong, because it contains a path that is not the input to the tool.

**Comment by PhilippWendler** [comment]
> For inspecting results using BenchExec's HTML tables, it was convenient that the benchmarking engineer could click on an entry in the table to open the input file. Any idea on how to achieve this?

Yes: The Javascript would load the Yaml file, parse it, and provide clickable links for all `input_files`. However, note that typically this still won't be helpful for input paths that are directories.

> `first_inputfile_name` perhaps?

I am not sure the first path (which may not even be a file) is "special" enough to warrant an extra variable. The full solution above would be preferred.

> Or, even more complete, offer a set or sequence:
> `inputfile_set` perhaps?

Variable expansion is just string manipulation, I don't see a way to handle sets there in a meaningful way.

**Comment by dbeyer** [comment]
I would like to use `taskdef_name` to refer to the task definition, because `inputfile_name` is wrong in this case (the .yml file is *not* given as input to the tool).
Should be easy to implement?

**Comment by dbeyer** [comment]
As for the `inputfile_name` I currently take just the first input from the task definition, because the set is a singleton in my case that I currently have to handle.  I added a column `program`, see:
https://test-comp.sosy-lab.org/2019/results/results-verified/prtest.2018-12-29_1321.results.test-comp19_prop-coverage-error-call.ReachSafety-BitVectors.xml.bz2.table.html

I do not like this solution much but I have no better means available currently.

**Comment by PhilippWendler** [comment]
Adding `taskdef_name` as alias for `inputfile_name` is of course easy, and I have added it.

Redefining `inputfile_name` would be a backwards-incompatible change (definitions that worked in BenchExec 1.17 would silently work differently in BenchExec 1.18), so I am hesitant to make that change now. Maybe for BenchExec 2?

**Comment by dbeyer** [comment]
Since it is a bug that `inputfile_name` refers to a task definition sometimes, I would not consider it a change of API, but rather a necessary correction.
Perhaps a release 1.17.1 should be done for only this and immediately.

I would find it more dramatic to change this after it was present for a long time,
while now it is there only since a couple of weeks and people will understand the fix
(and not many people are using this feature right now).

I do not know currently what would be a good fix.
Perhaps delete the variable `inputfile_name` whenever it points to a task definition.
(Are there applications where a task definition is actually the input?)
Then, the table generator could use, whenever `inputfile_name` is empty,
the contents of `taskdef_name` instead.
But perhaps this is more of a hack than leaving it as is ...
May be discuss in the group meeting to collect ideas?

**Comment by PhilippWendler** [comment]
> Then, the table generator could use, whenever `inputfile_name` is empty,
> the contents of `taskdef_name` instead.

So you are suggesting to keep the behavior exactly as is?

**Comment by dbeyer** [comment]
> > Then, the table generator could use, whenever `inputfile_name` is empty,
> > the contents of `taskdef_name` instead.
> 
> So you are suggesting to keep the behavior exactly as is?

I was suggesting to remove the content of `inputfile_name` if the task definition is given as YAML file,
such that nobody can mistakenly interpret the YAML file as name of the input file.
Is this the current behavior?

**Comment by PhilippWendler** [comment]
No.

But if we combine this suggestion with your other suggestion "Then, the table generator could use, whenever inputfile_name is empty, the contents of taskdef_name instead.", this seems like the current behavior (I don't understand where the difference would be).

**Comment by PhilippWendler** [comment]
For BenchExec 2.0 I am planning on changing the behavior such that `taskdef_name` is only defined if a task-definition file is used, and `inputfile_name` is defined only if no task-definition file is used (so they would be mutually exclusive). Is this appropriate for you?

**Comment by dbeyer** [comment]
Yes, this is exactly what I wanted.  Thanks!
