### ISSUE TITLE
Tool-info module with flexible tool name

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#397]
https://github.com/sosy-lab/benchexec/blob/ac991eabb53cfd1e4e7540b0b0d0abd2b1afa5ee/benchexec/tools/cpachecker.py#L92

Is it possible to ask the binary for the tool name, instead of hardcoding the tool name in the tool-info module?

Then we would not need additional tool-info modules for CPAtiger, CoVeriTest, etc.

**Comment by PhilippWendler** [comment]
To answer this question: Yes, it is possible.
