### ISSUE TITLE
clickable filenames if yaml-file is shown as overlay in html-table

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#402]
For the previous sv-benchmarks with the plain C-source-files the link to the sourcefile was showing an overlay window containing the plain source of the analyzed C-source-file. With the new yaml-scheme only the yaml is shown, which is nice, but not very helpful.

**Wanted feature**:
Parse the loaded yaml-file with some Javascript, replace filenames with links, and open those links in the overlay window, such that a user can show the C-source-file in the overlay.
The same could be done for property-files.
It would be sufficient to only replace those parts of the shown yaml, where filenames are expected.

After the above got implemented, having a "back to yaml"-button would be a nice bonus feature.

**Comment by kfriedberger** [comment]
I myself and several students want to look at the table and have a possibility to directly access the sourcecode. This is not possible since a several months now. I would either like to have #419 merged or at least see that someone is really working on this. 

Philipp only said that #419 is not good enough, but currently I have not yet seen any case where it would not work. Could Philipp provide a better solution or at least give a hint on his idea of a better solution. What are the required features for this (beyond the given description above)?

**Comment by PhilippWendler** [comment]
> I myself and several students want to look at the table and have a possibility to directly access the sourcecode. This is not possible since a several months now. I would either like to have #419 merged or at least see that someone is really working on this.

Currently all people who are active on BenchExec unfortunately have more important tasks, and thus I cannot make any ETA promises.

> Philipp only said that #419 is not good enough, but currently I have not yet seen any case where it would not work.

This is wrong, it was already in my very first reponse: https://github.com/sosy-lab/benchexec/pull/419#issuecomment-458616730

> Could Philipp provide a better solution or at least give a hint on his idea of a better solution. What are the required features for this (beyond the given description above)?

A better solution is suggested already in your very own issue description (https://github.com/sosy-lab/benchexec/issues/402#issue-397575406), which I agreed on (https://github.com/sosy-lab/benchexec/issues/402#issuecomment-452975276): We parse the file using a YAML parser (for which certainly Javascript libraries exist), extract the relevant info, and show it as links.

To make it easier than replacing only the links inside the shown YAML text (which I guess could be tricky), we could also show the task definition file in the overlay: first with all information extracted and printed out in a consistent and structured way, and below that the raw YAML file. The first part would have the links. This would have the additional benefit that users could for example expect that input files are always shown first and properties second (in the raw YAML file, the order could be different).

**Comment by kfriedberger** [comment]
Is there any way that someone implements a solution for this issue before starting SV-COMP?
For debugging wrong results in any benchmark, I (and also other users) simply want to click on the button the task and have any way to directly show the corresponding source file. It is really bad user experience to need to copy the URL and change the file ending and then start a second program (i.e., editor) to see the source code, if the solution (simply clicking on the filename) is already available in #419. 
Until now there seems to be no progress in this issue. I would prefer to merge my solution from #419 (that already works for most SV-COMP benchmark tasks, i.e., the main target of this application), until another developer improves the situation.

**Comment by PhilippWendler** [comment]
> Is there any way that someone implements a solution for this issue before starting SV-COMP?

Sure, we just need to find somebody who implements a proper solution based on the work in branch `react-table`.

A proper solution would look as described in https://github.com/sosy-lab/benchexec/issues/402#issuecomment-498116825 (rationale in https://github.com/sosy-lab/benchexec/pull/419#issuecomment-458852554). The work in branch `react-table` will make that even easier, because it adds a proper software architecture and dependency handling using `npm`. There are [several YAML parsers](https://www.npmjs.com/search?q=yaml) available for `npm`.

**Comment by PhilippWendler** [comment]
Some more information:
- Description of these YAML files is [here](https://github.com/sosy-lab/benchexec/blob/master/doc/benchexec.md#task-definition-files).
- Our demo table does not link to such files, but [this example](https://buildbot.sosy-lab.org/cpachecker/#/builders/11/builds/512) for example does.
- The development environment for the JavaScript code currently does not provide such task-definition files. Maybe it is easy to add some kind of mock for local testing. If not, one can use the following command to produce a table using the latest code that was bundled with `npm run build`: `bin/table-generator https://buildbot.sosy-lab.org/cpachecker/results/bam/00512.-r32971_integration-bam.2020-03-18_1529.results.xml.bz2 --show`
