### ISSUE TITLE
Table-generator: Overview level

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#423]
Currently, for a given set of benchmark-results (XML files),
table-generator generates one huge table.

The large tables are nice to have a look at details,
however, for getting a quick overview, they are too slow to load.

It would be nice to have, in addition, an overview table (dashboard view) generated
that presents a coarser view on the benchmark results.

First proposal: Omit all results rows, and most of the header, and print only the bottom statistics.
One statistics block for each column (benchmark tool or configuration) and for each vertical block as well (if the input table definition has a `union`).

Either always written (like the csv currently) or only if an extra parameter is given.

**Comment by VishalBhosale5** [comment]
can I take up an issue please
