### ISSUE TITLE
Drop Support for Expected Results and Scores without Task-Definition Files?

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#439]
Currently, BenchExec has two modes for checking expected results and computing (SV-COMP) scores:
1. If [task-definition files](https://github.com/sosy-lab/benchexec/blob/master/doc/benchexec.md#task-definition-files) are used, arbitrary property files can be used (since BenchExec 1.17).
2. [Without task-definition files](https://github.com/sosy-lab/benchexec/blob/master/doc/properties/INDEX.md#usage-without-task-definition-files) a specific set of properties (mostly from SV-COMP) can be used and the expected result needs to be encoded in the file name.

The second mode is historical and no longer recommended. The code for it in BenchExec complicates the result handling and it would simplify things if we could remove it.
Replicating old experiments (e.g., old SV-COMP instances) would get a little bit more difficult, but would still be possible (one could simply generate task-definition files for tasks in the old format). Furthermore, SV-COMP switched to task-definition files in 2019, and if we remove the legacy mode in 2020, already two instances of SV-COMP with the new format will have had taken place.

To clarify: Tasks could still be defined without task-definition files, BenchExec would just no longer check the correctness of the result nor compute scores.

Please comment here if you still have a use case for the historical mode and it would create problems for you to migrate.

**Comment by dbeyer** [comment]
Question: For replicating old experiments, I could just use an old release of BenchExec without trouble, correct?

**Comment by PhilippWendler** [comment]
Several possibilities:
- use old version of BenchExec (but of course you will miss all the nice improvements of newer BenchExec, so I would not recommend that)
- just run with new version of BenchExec, you will only miss checking for expected results and score computation (during replication, I guess the main goal would be to compare against the old results anyway)
- generate task-definition files for the old tasks with the script that we provide and just run the experiment with these (this won't affect how the tool sees the tasks, so the results will still be comparable)

**Comment by dbeyer** [comment]
I am in favor of dropping support for expected results in file names.

**Comment by PhilippWendler** [comment]
This was already decided a few months ago :-)

**Comment by dbeyer** [comment]
But not documented!

**Comment by dbeyer** [comment]
... and the issue was not closed.

**Comment by PhilippWendler** [comment]
Because the implementation is not finished yet. We will close it when this is done by labeling the commit as usually.

**Comment by dbeyer** [comment]
ok
