### ISSUE TITLE
CPAchecker-Wrapper does not parse Logfiles deterministically after Timeout

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#441]
The current version of Benchexec within CPAchecker does sometimes not add additional info about exceptions on timeout.
In [this table](https://buildbot.sosy-lab.org/cpachecker/results/bam/00150.bam.diff.html) the last column contains several `timeout (assertion)` which are not visible in the previous column.
The logfiles for the task `benchmarks/seq-mthreaded-reduced/pals_lcr.5.ufo.BOUNDED-10.pals.c.v+lhb-reducer.yml` seem to be identical and all include the exception/assertion.

Does anyone know the reason?

**Comment by kfriedberger** [comment]
It seems to be related with CPAchecker terminating itself internally forcefully or not.
There are two lines:
<pre>
Warning: Analysis interrupted (The JVM is shutting down, probably because Ctrl+C was pressed.) (ShutdownNotifier.shutdownIfNecessary, WARNING)
</pre>
and 
<pre>

Shutdown requested (The CPU-time limit of 60s has elapsed.), waiting for termination. (ForceTerminationOnShutdown$1.shutdownRequested, WARNING)
Warning: Analysis interrupted (The CPU-time limit of 60s has elapsed.) (ShutdownNotifier.shutdownIfNecessary, WARNING)
</pre>.
Either of both causes a different status in the table.
Perhaps we want to unify the status for both?

**Comment by PhilippWendler** [comment]
Could you provide a PR with what you propose? Or at least a more concrete suggestion?

**Comment by PhilippWendler** [comment]
Ping @kfriedberger?

**Comment by kfriedberger** [comment]
If you are asking for a concrete suggestion:
Always search for exceptions in the log, even if a timeut occured, and provide them for the user.
I do not yet have a PR for that.

A concrete example (from the table mentioned above) would be:
- [log1](https://buildbot.sosy-lab.org/cpachecker/results/bam/00149.-r31516_integration-bam.2019-07-19_2000.logfiles/pals_lcr-var-start-time.5.2.ufo.BOUNDED-10.pals.c.v%2Blhb-reducer.yml.log) parsed into "TIMEOUT"
- [log2](https://buildbot.sosy-lab.org/cpachecker/results/bam/00148.-r31515_integration-bam.2019-07-19_1908.logfiles/pals_lcr-var-start-time.5.2.ufo.BOUNDED-10.pals.c.v%2Blhb-reducer.yml.log) parsed into "TIMEOUT (assertion)"

**Comment by PhilippWendler** [comment]
The reason is this:
https://github.com/sosy-lab/benchexec/blob/96c828de7970a9dea7fa52c33ee8ec67c8642768/benchexec/tools/cpachecker.py#L165-L168
Assertions and exceptions are only reported if the return code is 0 or 1. In other cases (like JVM terminating because of timeout signal with return code 143) they are ignored. I guess we can change this, or do you fear that then assertions could mask more severe results like segfaults?

**Comment by kfriedberger** [comment]
In my opitnion, we should change this behaviour and get more info about exceptions.

Why not check for status like timeout/segfault/real_result and always (independently) add additional info about errors/exceptions/assertions from the log?

**Comment by PhilippWendler** [comment]
For timeouts, this is exactly what BenchExec does.

**Comment by kfriedberger** [comment]
As CPAchecker terminates itself shortly before reaching the hard timeout to print statistics, I would consider this as timeout as well and also look for exceptions.
