### ISSUE TITLE
Deadlock in Benchmark.py when executable file is invalid.

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#449]
When executing benchmark.py on current CPAchecker trunk (r32082) without a valid executable of the tool, the script hangs forever and can not even be killed via `crtl-c`. As there is only little overhead in CPAchecker's script, I assume that the problem is based on the newly integrated Benchexec.
It seems that all errors before actually starting the benchmarking process will cause a deadlock in the script. The real script `benchexec` (installed in release 2.2) does also not terminate and additionally does not produce any colorful output in the terminal (which might be another bug? or is this intended?).

## Steps to reproduce in CPAchecker:
- `chmod -x scripts/cpa.sh`
- `scripts/benchmark.py test/test-sets/integration-bam.xml`

## Output:  
<pre>[echo] [...]
BUILD SUCCESSFUL
Total time: 5 seconds
ERROR: Could not find 'cpa.sh' executable, but found file './cpa.sh' that is not executable.
// ------ hanging here forever, without the possibility to be interrupted
^Ckilling subprocesses...
^Ckilling subprocesses...
^Ckilling subprocesses...
</pre>

## The same problem appears:
- when using the VCloud via the direct client, but not via the web-interface. Example:
  - `chmod -x scripts/cpa.sh`
  - `scripts/benchmark.py test/test-sets/integration-bam.xml`
- when using other tools than CPAchecker, if the expected executable file is not available. Example:
  - `scripts/benchmark.py some-other-tool-testset.xml` (just replace the toolname in the XML-file with something else than `cpachecker`, e.g., `ultimateautomizer`).
- when using other tools than CPAchecker, if the tools executable is valid and in the `PATH` environment variable, but not in the current directory. Example:
  - download and unzip `https://gitlab.com/sosy-lab/sv-comp/archives-2019/raw/master/2019/uautomizer.zip` as a sibling of CPAchecker
  - `export PATH=$PATH:../UAutomizer-linux/` in the CPAchecker directory
  - `scripts/benchmark.py uautomizer-testset.xml` (without switching into the Ultimate directory!)
  - the log will tell you that it `Could not find Ultimate executable in '../UAutomizer-linux/Ultimate.py' or '/home/fri/workspace/cpachecker'`. However, `../UAutomizer-linux/Ultimate.py` is valid and executable.

**Comment by PhilippWendler** [comment]
As a note: Please do not clutter the issue description with information about other scripts and systems, if BenchExec itself is affected then this is enough information. And if it is not affected, then the issue is off-topic here.

> The real script `benchexec` (installed in release 2.2) does also not terminate and additionally does not produce any colorful output in the terminal (which might be another bug? or is this intended?).

This is explained in the [installation documentation](https://github.com/sosy-lab/benchexec/blob/master/doc/INSTALL.md#download-and-installation), the package `coloredlogs` is needed if you want this.
