### ISSUE TITLE
Error message on AttributeError is misleading

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#450]
With BenchExec 2.0 a new `config` parameter was introduced. If there is an attribute missing in that config, an `AttributeError` occurs in the following `try` block:
https://github.com/sosy-lab/benchexec/blob/ce141dea0c37d30565f3247c46da26b0a0a94b83/benchexec/model.py#L124-L140

The message in the corresponding catch clause is now misleading.
In addition, printing a textual representation of the error message would improve the usefulness and help to pinpoint why the error occurred.
In my example the `AttributeError` object would tell the real cause of why the error occurred:

    'MyConfigClass' object has no attribute 'hidden_dir'

**Comment by PhilippWendler** [comment]
When does such an error occur? This seems like a bug and an `AttributeError` is the appropriate result for such a bug.

**Comment by MartinSpiessl** [comment]
>When does such an error occur?

I had this problem here: https://gitlab.com/sosy-lab/sv-comp/archives-2020/merge_requests/1  
`check.py` in the archives-2020 repo now need the additional `config` parameter for one of the benchexec functions.definitely
Since there is currently no `Config` class provided in BenchExec (only the one in `test.py`, but I prefer not to depend on code in a test module), I cooked up my own one as a hotfix. This would not be needed if BenchExec provided a proper Config class for end users.

> This seems like a bug and an AttributeError is the appropriate result for such a bug.

Yes, I have no problem with the `AttributeError`, only with the text that is shown when the error occurs:

    'The module "{0}" does not define the necessary class "Tool", ' 
    "it cannot be used as tool info for BenchExec.".format(tool_module) 

It make assumptions about the cause of the error that are not always true and it hides the string representation of the error object, which would otherwise have shown what is really going on.

**Comment by PhilippWendler** [comment]
Well, this function is definitely not public API anyway and can change at any point in time. It is not intended to be called from the outside and it does not make sense to add code that checks for missing attributes in internal methods.

**Comment by MartinSpiessl** [comment]
Still, showing the error message would improve the code imho, regardless of whether it is public or not.  

The names also don't start with underscores so everyone will assume it IS part of the public API (in python, declarations starting with `_` are not imported on a wildcard import, as this is pythonic way of declaring something as private).

What about providing a way to check the information that the `archives-20*` repositories need as part of benchexec then? For example as a script in the `contrib` folder? This would get rid of the usage of the non-public API in the `archives-20*` repo and ease maintenance.

**Comment by PhilippWendler** [comment]
`benchexec` does not offer a public API at all, and its API is not [documented](https://github.com/sosy-lab/benchexec/blob/master/doc/benchexec.md), so all of it needs to be assumed to be private, naming convention or not.

> What about providing a way to check the information that the `archives-20*` repositories need as part of benchexec then? For example as a script in the `contrib` folder? This would get rid of the usage of the non-public API in the `archives-20*` repo and ease maintenance.

I do not know what kind of information this needs. Please file a proper feature request or PR to add such a script.
