### ISSUE TITLE
Drop support for table-generator --static-table

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#479]
After merging support for generating the new dynamic react tables, table-generator can still generate the old kind of HTML tables with `--static-table`. We should remove this in the next major version if nobody complains.

**Comment by dbeyer** [comment]
Don't we have extra work with maintaining the code, tests, etc. for the old tables?
Remove immediately? Or is Release 3.0 planned in the near future anyway?

**Comment by PhilippWendler** [comment]
Tests for old tables have mostly been removed already. Keeping the code is currently holding up some refactoring but not adding extra effort (where we do the refactoring now or in a few weeks/months is not important). Release 3.0 is planned for [January](https://github.com/sosy-lab/benchexec/milestone/8).
