### ISSUE TITLE
Multi-select column filter for status columns in react table

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#481]
The filter feature for status columns in the react table currently allows to select exactly one status or category value to be used as filter. We could extend this to allow selecting several different values, for example, in order to allow showing lines with certain errors, but without showing all errors.

The UI could look like the file filter of GitHub's PRs:
![Screenshot_2019-11-02 sosy-lab benchexec](https://user-images.githubusercontent.com/2545335/68068659-5ade2200-fd57-11e9-8b01-46340c51c45f.png)

**Comment by kfriedberger** [comment]
I would like to have this feature again, as in the older tables. It is quite helpful when filtering for related statuses like `TIMEOUT`/`TIMEOUT(exception)`/`TIMEOUT(assertion)`.

**Comment by PhilippWendler** [comment]
Of course. For now I suggest to filter on category and then sort by status.

**Comment by PhilippWendler** [comment]
A first improvement would be to have negated filters (e.g., `not correct` as category). This would be easy to implement if we find a UI solution that works with the current drop-down field and is still understandable. Any suggestions?

**Comment by lembergerth** [comment]
How about clicking once on an item selects it, and clicking twice negates
it? A third click could disable it again.
The current selection could be signaled by showing a filled or checked
checkbox for the first, and a minus-sign in the checkbox for the second.

**Comment by PhilippWendler** [comment]
This is not possible in a standard drop-down field I guess.
