### ISSUE TITLE
Bolder separation of the columns for different tools

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#487]
It is difficult when scrolling through the columns to see when a new column group starts for a new configuration/tool. For both tabs "Summary" and "Table".

**Comment by PhilippWendler** [comment]
I agree that this would be nice, but it is difficult to implement. We need to apply a specific CSS style to the left-most or right-most **currently visible** column of each tool. And currently the code never explicitly calculates this information, we just generate all columns as a flat list (not grouped in column groups) and set some of them as invisible.

So probably this won't be implemented soon.

**Comment by dbeyer** [comment]
Hmmm.  Perhaps make the text in the status column bold-face, in order to indicate the start of a new column group?

**Comment by dbeyer** [comment]
Also, the constant width (issue #492) makes it easy to loose orientation. The different widths of the columns gave the column groups a certain "shape" that made me easily recognize the structure of the whole table.

**Comment by PhilippWendler** [comment]
Make the status column bold would work, but it makes it quite "heavy" looking, because almost nothing else in the UI (and nothing in the table itself) is bold.

You can try it easily by adding the following CSS rule temporarily with the browser development rules:
```
.rt-td:nth-child(2) {
    font-weight: bold;
```
Do you prefer this?

**Comment by PhilippWendler** [comment]
I found a solution for a border between different run sets: we can add a dummy column with a few pixels width and a dark background. All interaction with these dummy columns (resizing, filtering, sorting) would be disabled.

However, I need to do some refactoring first.
