### ISSUE TITLE
Last clicked Cell is no longer highlighted

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#494]
In the old table, the last clicked cell got a **red border**. This feature is missing in the new table.

For me, column-wise comparison of tasks in larger tables is much easier if I see (red border) where I previously clicked on a logfile.

Short historical trip: there was a special request from a lion to implement this feature once :-)

**Comment by PhilippWendler** [comment]
The last clicked cell should still have the focus after the modal is closed, so it should have the small border that shows focus. Is this enough?

It is probably better visible now after eaaa4b6b, and if it does not work for you please make sure you test with 8fcf67c3 or newer, because the implementation of the overlay changed.

**Comment by kfriedberger** [comment]
The focus is browser-defined and does only show up in Firefox (and even MS-Edge), but not in Chromium. I can step through all links with TAB and they get hightlighted in Chormium. However, after a mouseclick no cell has a border.

**Comment by PhilippWendler** [comment]
Chromium again... (╯°□°)╯︵ ┻━┻

Is it ok if we use the focus feature of the browser and just add CSS that styles it? That means the highlight is gone as soon as something else is focused.

We could do it like this for example (`outline: 1px dotted red;`):
![grafik](https://user-images.githubusercontent.com/2545335/68391941-f3fea580-0168-11ea-9c00-ba4da66d09af.png)

Or like this (`outline: 1px solid red;`)?
![grafik](https://user-images.githubusercontent.com/2545335/68391964-011b9480-0169-11ea-862f-6261b14229bd.png)

Any other suggestions?

**Comment by kfriedberger** [comment]
Just changing the CSS will not help for Chromium :-(
The focus is never set on a cell when clicking on it.
Perhaps we need to use "element.focus()" somewhere.

**Comment by PhilippWendler** [comment]
It works for me (I tested in Chromium before making the suggestion). And there is already an `element.focus()` somewhere, because our library for modals ensures that focus is restored after the modal is closed.
