### ISSUE TITLE
Allow filtering by property

### ISSUE THREAD

**Issue by lembergerth** [sosy-lab/benchexec#496]
In the HTML table, is it possible to filter rows by property?

Given a table that contains rows with results with both properties `unreach-call` and `no-overflows`,
I'd like to tell the table to only show me (and work on) tasks with property `unreach-call`.

While the property is shown in the first column of the "Table" table, it is not possible to filter by it.

**Comment by PhilippWendler** [comment]
Actually it seems I broke filtering of the first column completely. Will fix this soon.
