### ISSUE TITLE
Logfile in Overlay not shown for Local Table using GoogleChromium.

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#499]
Tables generated with `BenchExec 2.3-dev` (CPAchecker r32231) do not show the content of logfiles in GoogleChromium webbrowser when opened from local disk (i.e., directly after benchmark execution). Firefox works fine, GoogleChromium has problems.

Looking into the browser's JS debug console, I found the error 
<pre>load content bmc.2019-11-11_1257.logfiles/k1-mathsat5.floppy_simpl3.cil-1.yml.log
Fetch API cannot load file:///[...]/bmc.2019-11-11_1257.logfiles/k1-mathsat5.floppy_simpl3.cil-1.yml.log. URL scheme "file" is not supported.
Fetch API cannot load file:///[...]/bmc.2019-11-11_1257.logfiles.zip. URL scheme "file" is not supported.
Uncaught (in promise) TypeError: Failed to fetch
</pre>

As the JS is minified, debugging this is quite hard at that place.

**Comment by PhilippWendler** [comment]
This should be a Chromium problem and not related to the new tables. Please double-check with an old table. Please also try `--allow-file-access-from-files` for Chromium.

**Comment by PhilippWendler** [comment]
Ok, there was a bug that the error message was not shown. Now this is restored and should have the same behavior as in the old table implementation. AFAIK there is nothing that we can do to improve the situation. Please confirm and close this issue.

**Comment by kfriedberger** [comment]
**Positive**: now I see the error message.
**Negative**: In the very same browser instance, logfiles in old tables work fine, logfiles in new tables do not.

Might this issue be related to #501?
I would like to not close this issue, because it is still unsolved.

**Comment by PhilippWendler** [comment]
The only explanation is that it is indeed related to #501, though I have no idea why. If anything, the old code that attempts to access individual parts of the ZIP file via ranged HTTP requests should have more problems accessing local files than the new code that just loads the whole file.

We can test again after #501 is solved. Apart from that I would not know what to  do.

As workaround, you can start a local HTTP server that serves files from that directory. There are a lot of such tools, for example built-in ones in PHP (`php -S`) and Python (`python -m http.server`) or as a [NPM package](https://www.npmjs.com/package/http-server).
