### ISSUE TITLE
QuantilePlot is Wrong when Showing Direct Results

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#500]
On the old tables, the `direct plot` showed the actual task name as x-axis. This seems to have changed. The data is just unsorted and left-aligned for the direct plot, without any change on the x-axis labelling. Is this the intended behaviour?

**If this is the intended behaviour, then this issue is invalid and can be closed.**

**If this is not an intended behaviour, then there is the following bug:**
For incomplete data sets (or comparisons of benchmark sets with a different number of tasks), the quantile plot when showing direct results is invalid.

How to reproduce:
- open https://buildbot.sosy-lab.org/cpachecker/results/nightly-sv-comp/00115.nightly-sv-comp.diff.html
- click on `Quantile Plot`
- click on `Switch to Direct Plot`
- the blue-ish data lines in the top left corner use the wrong x-value. The orange data line on the bottom is correct.

**Comment by PhilippWendler** [comment]
The labels of the x axis were pretty unusable in the old table, so they got removed, yes. For this there are the tooltips now.

But the left-aligned data is obviously not intended.
