### ISSUE TITLE
Recursive padding in table cell adds unnecessary paddings

### ISSUE THREAD

**Issue by lembergerth** [sosy-lab/benchexec#505]
The CSS of the new tables has the following entry:

```css
.mainTable .rt-tbody .rt-td *{padding:6px 2px}
```

Because of the wildcard `*` , this padding is added for each additional nesting within a cell's HTML.
This adds unnecessary padding and increases the size of rows when using own HTML that is not completely flat.

is there some good reason for the wildcard?
By my own preference, the tables I've looked at actually look better without that CSS entry because they are more condensed.
Thus, I suggest to remove the entry.

Find a comparison in the image below (top: without entry, bottom: with entry, with a custom HTML cell with a single `<div>` container inside)

![2019-11-14-160840_1920x1080_scrot](https://user-images.githubusercontent.com/4499519/68906476-3724bf80-06f9-11ea-8d4a-7853fbb3e422.png)

**Comment by PhilippWendler** [comment]
The wildcard is there only for technical reasons (72f3ef2844376dad8e9d377d2756c845fc3ac310), what I actually wanted to do is a `.mainTable .rt-tbody .rt-td > *` selector (only immediate children).

Your screenshots do not show an actual table, they show a modified table, and only because of this it looks ok without padding. A standard table without padding would look too dense.

But I can find a different solution such that only immediate children are affected.

**Comment by lembergerth** [comment]
> Your screenshots do not show an actual table, they show a modified table, and only because of this it looks ok without padding. A standard table without padding would look too dense.

Ok, so I chose a bad example for that argument because I wanted to show the recursive padding.

Here's an unmodified table, with and without the existing padding; I still prefer the denser view because you can see a lot more information at once. I guess this comes down to personal preference, but maybe you'd still consider decreasing the padding? Right now there's at least 12px space between two numbers, which would fit one full additional number in the common font sizes.

![2019-11-15-035440_1920x1080_scrot](https://user-images.githubusercontent.com/4499519/68942055-5b65b800-075c-11ea-97d2-5fcd86d4e4a1.png)

**Comment by PhilippWendler** [comment]
In this table, each column is extremely wide with lots of whitespace because you have only a few columns and a wide screen.

Do you still prefer this dense view if you have lots of small columns and their content fills the whole cells?

**Comment by lembergerth** [comment]
To simulate a more dense table, I shrank the column width of the example:
(left: current state. right: no additional padding of cell content)

![2019-11-15-072703_1920x1080_scrot](https://user-images.githubusercontent.com/4499519/68954843-ab9f4300-0779-11ea-800b-662fb07aff19.png)

I think the cell borders are a bit of an eye-strain now, but I still like that you can get so much more information on one page.
The main task of the tables is to present information. So if more information is presented at once, the tables do a better job.
For our old tables, I've heard that people even scaled the page size down to fit more information on one screen; by decreasing the padding, we could give that to them for free.

If you think no padding is too extreme, how about decreasing the vertical padding from 6px to 2px?
I think this still gives good results.

**Comment by PhilippWendler** [comment]
I closed this issue because the problem described in the title is fixed. Reducing padding can be discussed separately if still desired.
