### ISSUE TITLE
Remove hard-coded SV-COMP properties from BenchExec?

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#508]
Currently, BenchExec contains a hard-coded list of [SV-COMP](https://sv-comp.sosy-lab.org) properties with lots of [information about them](https://github.com/sosy-lab/benchexec/blob/8230a5169f17025cca7d77f7a3ab5978b96261ab/benchexec/result.py#L112-L207). After #439 is implemented this list serves only one remaining purpose:

If the property of a run is one of these hard-coded properties (e.g. `unreach-call`) and a verifier reports a result of the form `false(...)` with `...` being different from the SV-COMP name of the respective property, BenchExec will categorize the result as `unknown` instead of `correct` or `wrong` ([test case that shows this](https://github.com/sosy-lab/benchexec/blob/8230a5169f17025cca7d77f7a3ab5978b96261ab/benchexec/test_result.py#L937)).

For non-SV-COMP properties, BenchExec allows arbitrary results of the form `false(...)` ([test case that shows this](https://github.com/sosy-lab/benchexec/blob/8230a5169f17025cca7d77f7a3ab5978b96261ab/benchexec/test_result.py#L909)).

All this is completely independent from the case where subproperties exist (e.g., SV-COMP's `memsafety` property). If subproperties exist, the violated subproperty needs to be specified in the task-definition file and BenchExec always checks whether expected and actually reported subproperties match.

So we could remove this SV-COMP-specific check and the hard-coded list of SV-COMP properties and let BenchExec treat all properties in the same way, regardless of where they come from (with the exception that SV-COMP scores will still be computed if the property looks like an SV-COMP property).

Not sure whether we should do this together with #439 for [release 3.0](https://github.com/sosy-lab/benchexec/milestone/8) or wait longer.

**Comment by PhilippWendler** [comment]
@dbeyer What do you think? Should we do this now or wait?

**Comment by dbeyer** [comment]
As soon as possible, please.  What a deletion party we can celebrate!  How many lines?

Thanks a lot!
