### ISSUE TITLE
Reduce vertical padding of table rows to use space wisely

### ISSUE THREAD

**Issue by lembergerth** [sosy-lab/benchexec#509]
As shown and discussed in #505 , we could reduce the vertical padding between table rows to make more information available at once.
This has the potential to show more than 50% more information on the same space.

**Comment by PhilippWendler** [comment]
I guess we could shrink the vertical padding from 8px to 6px, it still looks good if we also make the horizontal borders less visible (same light gray as the vertical borders).

Suggestion:
![grafik](https://user-images.githubusercontent.com/2545335/88636071-beb03400-d0b8-11ea-98a1-28a43b5c5ae1.png)

Current:
![grafik](https://user-images.githubusercontent.com/2545335/88636111-c7a10580-d0b8-11ea-9545-fe6eb27ab2e2.png)

What do you think?

**Comment by lembergerth** [comment]
I like it! 👍 
The change in the value columns is hardly visible in my opinion, but you can already see 2 1/2 more rows.
