### ISSUE TITLE
Table does not resize vertically on window-size change

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#513]
When I zoom out in the table tab (e.g. by pressing ctrl+- multiple times) I expect the table to fill out at least the same percentage of my browser window.
Currently, the number of rows visible seems to be fixed, so the table shrinks until almost my whole screen is empty.
![tables](https://user-images.githubusercontent.com/33026673/69012800-26cf4780-097a-11ea-8870-67cd3336f3a7.jpg)

**Comment by MartinSpiessl** [comment]
I just realized I tool a bad table as example, because it has only a few entries. The problem also exists if you take a table with >100 entries, i.e., of there are more rows than can be displayed.

**Comment by PhilippWendler** [comment]
Also happens when resizing the window. A workaround is to reload the page.

I do not know how to solve this unfortunately.
