### ISSUE TITLE
Easier way to load development environment with other tables

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#515]
Our setup for development of the new HTML tables has the command `npm start` that starts a web server with an example table in development mode (non-minified build, debug mode of React, live reload after corresponding files change). This is nice and useful, but by default always uses the same [small table](https://github.com/sosy-lab/benchexec/blob/master/benchexec/tablegenerator/react-table/src/data/data.json). Furthermore, the code that is responsible for this is part of the main code, not part of the test code or the development scripts (but at least it is just 3 lines).

It is already possible to use the development mode with all of our [test tables](https://github.com/sosy-lab/benchexec/tree/master/benchexec/tablegenerator/test_integration/expected) if one replaces `data.json` with  a hardlink to one of the test tables (the `.html` files, which actually contain pure JSON), but this could be improved:

- Provide a way to pass the desired test table as parameter to `npm start`, without need for hardlinks or symlinks.
- Provide a way to specify an arbitrary existing HTML table as source of the data and not only files that contain only the pure JSON. Everything except the JSON data should then be ignored.

**Comment by DennisSimon** [comment]
This would definitely be a huge dev experience improvement.
Will look into creating something for this this evening.
