### ISSUE TITLE
Score-based quantile plots in HTML table

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#516]
SV-COMP uses score-based quantile plots for presenting results, which have some advantages over reqular quantile plots. We could add these as a variant on the tab with the quantile plot (and probably make it the default if all tasks in the table have a score).

Explanation of score-based quantile plots is for example in our [paper, Section 7.8](https://www.sosy-lab.org/research/pub/2019-STTT.Reliable_Benchmarking_Requirements_and_Solutions.pdf).

**Comment by PhilippWendler** [comment]
This plot type would be available only if there are scores in the table. If all runs have scores, I see no reason against making it the default, but maybe we should not make it the default if only some runs have scores? Or would that be too confusing?

In any case, if the score-based quantile plot is selected, the (future) drop down for Results (all/correct only) needs to be disabled and should probably show a blank value (because for score-based quantile plots the choice of visible results is defined). We could also hide it, but I guess showing it in disabled state is less confusing.

**Comment by lachnerm** [comment]
I have started to implement a solution for this new plot type. However, there are still a few things I'm missing or not sure about how to handle them:

- Where can I see whether there is a scoring scheme defined for the runset and where can I find it? Or do we use a fixed scoring scheme?
- In case it's not already defined in the scheme: Besides `correct` & `incorrect` I have also encountered the categories `wrong` & `missing` for some results. How are those handled with regard to the score-based plot?
- Is the option `Score-based Quantile Plot` supposed to be shown (possibly disabled) even if there are no runsets that support scoring?
- In case a column is selected with the score-based plot type, are runsets that contain this column and don't support scoring supposed to be hidden? Is this combination even possible in practice?

**Comment by PhilippWendler** [comment]
>  * Where can I see whether there is a scoring scheme defined for the runset and where can I find it? Or do we use a fixed scoring scheme?

Currently, there is only one supported scoring scheme, the one from [SV-COMP](https://sv-comp.sosy-lab.org/2020/rules.php#scores). But I think we should not need to implement this information in the HTML table, and instead just read the scores from the JSON data.

>  * In case it's not already defined in the scheme: Besides `correct` & `incorrect` I have also encountered the categories `wrong` & `missing` for some results. How are those handled with regard to the score-based plot?

`missing` means that no information about correctness of the result is available, and thus also no score. `incorrect` should not occur, but `wrong` means the same.

>  * Is the option `Score-based Quantile Plot` supposed to be shown (possibly disabled) even if there are no runsets that support scoring?

No.

>  * In case a column is selected with the score-based plot type, are runsets that contain this column and don't support scoring supposed to be hidden? Is this combination even possible in practice?

Yes, this is possible (although rare). Just not showing run sets without scores would be fine, I guess.
