### ISSUE TITLE
Columns with links to output file in HTML tables

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#52]
Provide a way to add columns to the HTML tables that contain a link to an output file of the tool, if it exists. This could be specified for example like this:
```
<column title="column title" type="link">file/name.txt</column>
```

**Comment by dbeyer** [comment]
The "if it exists" is not yet implemented.

The following is supported:
 <column title="witness" href="../results-verified/LOGDIRVERIFIED/sv-comp16.${inputfile_name}.files/error-witness.graphml">wit</column>
<column title="wit1_status" href="../results-validated/LOGDIRVALIDATED1/sv-comp16-witness.${inputfile_name}.log"/>

The first line defines a column that contains "wit" in each cell with a link to a row-dependent file.
The second line defines a column that contains the status from the raw XML data with a link to a row-dependent (log) file.
