### ISSUE TITLE
Incorrect handling of result status in `mergeBenchmarkSets.py`

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#541]
Since BenchExec 2.0, the results `false` and `false(unreach-call)` are considered to be equivalent.
The following line that is used to check whether the witness validation agrees with the verification does not reflect that:
https://github.com/sosy-lab/benchexec/blob/e041f9ac2d03b6bf11ac679be8849c50560d06b0/contrib/mergeBenchmarkSets.py#L70

Here, the validation is not recognized if e.g. the verification returns `false(unreach-call)` and the validation returns `false` or vice versa.

**Comment by dbeyer** [comment]
The validation has to return the same result, `false(unreach-call)` in this case.
If a validator reports just `false` then I should contact the developers to fix this.
But this is an SV-COMP issue, not a BenchExec issue.
