### ISSUE TITLE
The table for selecting columns does not correctly show missing columns

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#543]
I have two task-sets with different data-columns (one task-set has only a column `A`, the other task-set has columns `A` and `B`). Combining them side-by-side in one html-table works. However, the dialog (table) for selecting viewed columns does not show this correctly. Clicking seems to work properly, e.g., hiding and viewing a column (and also a complete set of identical-named columns) works as expected, and all columns are available. Just the view is invalid.

Example: see column `#reached`/`host`/`#blocks`/`#hits` in the appended screenshot.

![Table_Bug_BDD](https://user-images.githubusercontent.com/10998542/71885701-2b72d980-313b-11ea-8570-6c96e535e48c.png)

**Comment by PhilippWendler** [comment]
Information for reproducing:

Run `npm run start ../test_integration/expected/multi-table-with-columns.table.html` in our [development environment](https://github.com/sosy-lab/benchexec/tree/master/benchexec/tablegenerator/react-table) and open http://localhost:3000/. Then click on "Click here to select columns" in the header of the left-most column. The columns there should be aligned properly, such that each entry is below its respective header.

The code for this is https://github.com/sosy-lab/benchexec/blob/39a98d4ffe4fae3bc62d74819e8669cd4e1e0a4e/benchexec/tablegenerator/react-table/src/components/SelectColumn.js#L54-L73
It needs to do something more similar to the [code that renders the header](https://github.com/sosy-lab/benchexec/blob/39a98d4ffe4fae3bc62d74819e8669cd4e1e0a4e/benchexec/tablegenerator/react-table/src/components/SelectColumn.js#L75) and iterate over `this.selectable`.

Of course the behavior should not change, just the table layout.
