### ISSUE TITLE
Use of BenchExec

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/benchexec#553]
BenchExec has been extremely useful in the last couple of months for finding bugs in our Dartagnan tool (https://github.com/hernanponcedeleon/Dat3M).

Please feel free to name Dartagnan in the list of BenchExec users.

**Comment by PhilippWendler** [comment]
Thank you very much for your feedback, and nice to hear that BenchExec is useful! I added you to the Readme.
