### ISSUE TITLE
Tooltips for column title if less space

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#554]
Sometimes I have a very long name for a rundefinition and the table is just to narrow to show the complete title. I want to have a tooltip with the complete name for a column on mouseover.

![table](https://user-images.githubusercontent.com/10998542/76152578-550b9b00-60c1-11ea-818a-048ca445c04c.jpg)

**Comment by PhilippWendler** [comment]
Actually, this should be a browser feature, because the truncation including the ellipsis is also a browser feature.

For now, one can always resize the columns to see the full content.

**Comment by kfriedberger** [comment]
None of my browsers automatically adds a tooltip for a shortened title.
Could we add a functionality (based on CSS or Javascript) to show a tooltip in all cases where the browser renders a ellipsis?
I would like to have something like mentioned [here at StackOverflow](https://stackoverflow.com/questions/5474871/html-how-can-i-show-tooltip-only-when-ellipsis-is-activated).

**Comment by PhilippWendler** [comment]
> None of my browsers automatically adds a tooltip for a shortened title.

I know, just saying they should.

> Could we add a functionality (based on CSS or Javascript) to show a tooltip in all cases where the browser renders a ellipsis?

I would add a tooltip for the cells from your screenshot, but this is unconditional and would probably blow up the DOM if done for each and every HTML element.

But of course priority for this is not so high.

**Comment by kfriedberger** [comment]
Of course, the title-cells are sufficient. I never intended this feature for all cells.

Can we mark this issue as `hiwi/starter job`? I could not find such a label.
