### ISSUE TITLE
Different PATHs when running with `containerexec` or `benchexec`

### ISSUE THREAD

**Issue by stephanlukasczyk** [sosy-lab/benchexec#558]
I'm trying to isolate a program with BenchExec for benchmarking. My program is written in Python. I have both BenchExec and my program installed in the same virtual environment and I've encountered different behaviour when using `containerexec` or `benchexec` to start my runs.  The following describes the scenario using the [`sampleproject`](https://pypi.org/project/sampleproject/) instead of my program but shows the same:

## Steps to reproduce
Create a new virtual environment, install `sampleproject` and BenchExec to it and execute runs with `containerexec` or `benchexec` (I use `$` to mark commands, outputs are only given if they are of interest):
```console
$ virtualenv -p /usr/bin/python3 benchexec-text
$ source benchexec-test/bin/activate
$ pip install sampleproject==1.3.1 benchexec==2.5
$ sample
Call your main application code here

$ containerexec --read-only-dir / --keep-system-config --overlay-dir . -- sample
2020-03-18 08:42:44,073 - INFO - Starting command sample
2020-03-18 08:42:44,073 - INFO - LXCFS is not available, some host information like the uptime leaks into the container.
Call your main application code here

```
This obviously works as expected.  If I now change the last command of the sequence, I get the following:
```console
$ benchexec --read-only-dir / --keep-system-config --overlay-dir . -- sample
usage: benchexec [-h] [-d] [-r RUN_DEFINITION] [-t TASKS] [-n NAME]
                 [...omitted...]
                 FILE [FILE ...]
benchexec: error: File 'sample' does not exist.
```

## Expected behaviour

I'd have assumed that both command lines lead to the same result, i.e., they find and execute the `sample` program, like `containerexec` does. It looks like `benchexec` uses a different PATH to search for the program than `containerexec` does?!?  I am working on a Debian 10 machine (Kernel 4.19), Python version is 3.7.

Am I doing something wrong here, e.g., missing a parameter setting or something? Or is this intended behaviour?  I'd prefer to use `benchexec` over `containerexec`, if possible, since I'd be able to specify resource limits with the former.

**Comment by PhilippWendler** [comment]
`benchexec` cannot be used to execute a single command line, it is intended for benchmarking a large set of executions of the same tool. Therefore it needs to be given an [XML file with a benchmark definition](https://github.com/sosy-lab/benchexec/blob/master/doc/benchexec.md#input-for-benchexec) that defines which input files and command-line options to use, and it needs a [tool-info module](https://github.com/sosy-lab/benchexec/blob/master/doc/tool-integration.md) that defines how to actually execute the tool.

If you just want to execute a single command-line but with measurements, use [`runexec`](https://github.com/sosy-lab/benchexec/blob/master/doc/runexec.md).

**Comment by stephanlukasczyk** [comment]
Ah, thanks for your quick answer, @PhilippWendler . I missed that, sorry. `runexec` does the job as expected :blush:
