### ISSUE TITLE
Scatter plot layout broken with missing values

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#561]
There are some tables with columns, where the scatter plot cannot be shown.
I could not yet detect a reason.

For example, [this buildbot table](https://buildbot.sosy-lab.org/cpachecker/results/nightly-predicate/00117.-r32991_integration-nightly-predicate.2020-03-22_2200.results.html) has several columns with values in range `[0s;900s]`.

A scatter plot for the two columns `cputime` and `cex analysis` looks like all data points are just at the top border of the plot.
A scatter plot for the two columns `abstraction` and and `cex analysis` looks like a single point in the right top corner.

**Comment by PhilippWendler** [comment]
This occurs if not all entries in that column have a value.

Workaround: In the filter field for the column (e.g., `cex analysis`) enter `:`, which means "any possible (numeric) value" (interval from negative infinity to positive infinity).
