### ISSUE TITLE
Mouseover effect in Table for all Column Titles

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#564]
This might just be a small CSS change to improve usability.
I would like to have the same mouseover effect (highlighting) for all rows and columns,
i.e., all rows with light grey background, links with dark backgound.
This effect seems to be missing for the title of the data-table in the table-tab and also for the title of the statistics-table in the summary-tab.

Additonally, I would like to have a different highlighting for the text in the cell containing `Click here to select columns`, because the link from cell's text opens the selection dialog while the link from the cell's background sorts the task column. Also the tooltip `Click here to sort` for this special cell is missing (or maybe just not shown) on mouseover.

**Comment by PhilippWendler** [comment]
It might be easier to describe what you want if you just provide a few CSS rules for `:hover` of the respective cells, would you mind doing that?

**Comment by kfriedberger** [comment]
The CSS can be improved with 
<pre>
/* every column is clickable for sorting */
.mainTable .rt-resizable-header:hover{background-color:#d3d3d3}

/* every column with text is clickable for quantile plot */
#statistics .rt-resizable-header .columns:hover{background-color:#d3d3d3}

/* clickable text in clickable cell, special color needed */
.mainTable .selectColumns:hover{background-color:#f0f}

/* clickable text in normal cell, special color to be consistent with above */
#statistics .selectColumns:hover{background-color:#f0f}
</pre>

Could someone integrate this into the CSS of the template?

The tooltip seems to be missing. I could not yet figure out, from where is should come or why it is missing.
Highlighting the whole title row might not be needed, as every title cell is clickable anyway.

**Comment by PhilippWendler** [comment]
I did not use a separate color for the hover of the "Select columns" button, but I think it is acceptable as it is, because the background of that button is changed only if the user hovers over the button itself (so it stands out as a white rectangle when hovering over the remainder of the cell). In future CSS versions we might be able to handle this fully.
