### ISSUE TITLE
Buttons below plots in HTML table need clicking twice

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#577]
There is a regression in BenchExec 2.6: When opening the plot tabs of an HTML table and clicking on one of the buttons below the plot, only the URL content changes but the plot does not. Clicking on the button a second time fixes the plot.

**Comment by kfriedberger** [comment]
for example, try clicking on the buttons below the plot in [this table](https://buildbot.sosy-lab.org/cpachecker/results/induction/00586.-r33601_integration-induction.2020-05-19_2218.results.html#/scatter?linear=true).
