### ISSUE TITLE
Run table-generator tests under Windows

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#591]
There is no reason why `table-generator` should not work on Windows as well. Currently, we do not test this, however.

It should be relatively easy to add a Windows CI using [AppVeyor](https://www.appveyor.com/docs/lang/python/). The relevant command to execute only the table-generator tests would be `python3 setup.py nosetests --test benchexec.tablegenerator`.

I already enabled the project on AppVeyor, it should start running tests after `.appveyor.yml` is added to a branch.

**Comment by lachnerm** [comment]
Fixed in 044ecc680d6619081020a721c9f1afddf0bf2691.
