### ISSUE TITLE
score calculation for SV-COMP 2021 should take the result of the new witness linter into acount

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#603]
Last year we had some problems with the score calculation because a validator falsely flagged witnesses as invalid.
As a result, the code that prevents a witness from counting as validated was removed from [mergeBenchmarkSets.py](https://github.com/sosy-lab/benchexec/blob/master/contrib/mergeBenchmarkSets.py) via the following commit:  

https://github.com/sosy-lab/benchexec/commit/f34ee4503f3698e97090b89ff6bfc6e2040b4dc6

The idea came up to have a dedicated tool that syntactically checks the witnesses and decides whether these are syntactically valid or not. The tool currently resides on the branch https://github.com/sosy-lab/sv-witnesses/tree/witnessLinter

For SV-COMP 2021, the score computation should depend on the decision of the witness linter to decide whether a witness is syntactically invalid and therefore should not count as validated.

This will depend on the tool-info module for the witness linter, which is not yet written.

**Comment by PhilippWendler** [comment]
@MartinSpiessl Is https://github.com/sosy-lab/benchexec/commit/e9c3d2dff6c8678765a35baca74b345a4567caf0 what was intended here?

**Comment by PhilippWendler** [comment]
The script that handles this was moved here: https://gitlab.com/sosy-lab/benchmarking/competition-scripts/-/blob/main/prepare_tables/adjust_results_verifiers.py

If this issue is still relevant, it should be recreated there.
