### ISSUE TITLE
Weird issues with benchexec version

### ISSUE THREAD

**Issue by zvonimir** [sosy-lab/benchexec#605]
Ok, this is bizarre and I have no explanation for this behavior. Occasionally, when I install the latest benchexec release from the Debian package, `benchexec --version` reports `benchexec 2.3-dev` instead of `benchexec 3.2`. I am pretty sure this is happening even though I install it from the same package in both cases.

I know this sounds weird. Do you maybe have any reasonable explanation for this behavior?

Thanks!

**Comment by PhilippWendler** [comment]
Ok, this is indeed weird :-)

Just to make sure: You are talking about installation from [this package](https://github.com/sosy-lab/benchexec/releases/download/3.2/benchexec_3.2-1_all.deb) (which is linked from our releases page for BenchExec 3.2)?

Could you test whether it is actually BenchExec 2.3-dev or whether it behaves like BenchExec 3.2? (I suggest to go to our [changelog](https://github.com/sosy-lab/benchexec/releases) and pick one of the newer features that is easy for you to test, like the new table features)

I would guess that the most probable cause is some kind of duplicate installation.
What does `which benchexec` print?
Do you use virtual envs?
Did you at some point install with `pip`?
What do the following commands print? `pip list|grep BenchExec; pip list --user|grep BenchExec; pip3 list --user|grep BenchExec; pip3 list |grep BenchExec`

**Comment by PhilippWendler** [comment]
Did you find out more?

**Comment by zvonimir** [comment]
Nope, I haven't managed to reproduce it. Note that I was always installing it into a pristine Ubuntu 18.04 installation using emulab, and so there would not be any old packages there. So weird. Anyhow, I will close this and reopen if I encounter it again.
Thanks for your help!

**Comment by zvonimir** [comment]
It is back! So weird. I installed it into a pristine Ubuntu 18.04 and it was reporting 3.3 as its version. Now it is reporting 2.3-dev!
One thing I did (since I've been struggling with cgroups) is to follow these steps: https://github.com/sosy-lab/benchexec/blob/master/doc/INSTALL.md#setting-up-cgroups-on-machines-with-systemd
Could that somehow influence the printed version!?

Related to your suggestions, when I print out `benchexec --help` there is no `--tool-directory` option, and so I guess it is not version 3.3 after all.

Command `which benchexec` prints `/usr/bin/benchexec`.

I don't have pip or pip3 installed.

I will dig more.

**Comment by zvonimir** [comment]
I tried to install it again and I get `benchexec is already the newest version (3.3-1)` reported by apt.

**Comment by zvonimir** [comment]
So I did `sudo apt autoremove benchexec`. When I try to run it now, I get that it doesn't exist, as expected. When I installed it again (from 3.3 package), it is still reporting `2.3-dev` version.

**Comment by zvonimir** [comment]
Argh!!!! I got it!!!!!

So I have old benchexec source files on this same machine. To pick up SMACK tool python file, I would do:
```
export PYTHONPATH=$PYTHONPATH:/proj/SMACK/SMACKBenchResults/benchexec
```
And this would then somehow pick up old benchexec version from these sources!
Ok, closing this :). Sorry about the confusion.
