### ISSUE TITLE
Slicing (e.g. `run.output[1:10]`) does not work with `RunOutput` objects

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#614]
The following code will break if a slice is requested instead of a concrete, integer index:
https://github.com/sosy-lab/benchexec/blob/38e3d1f75499c32adb8273da6506c00db4d1e14b/benchexec/tools/template.py#L542-L543

example error message:
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/benchexec/benchexec/containerized_tool.py", line 256, in _call_tool_func
    return getattr(tool, name)(*args, **kwargs)
  File "/benchexec/benchexec/tools/myfancynewtoolmodule.py", line 43, in determine_result
    print(run.output[-3:])
  File "/benchexec/benchexec/tools/template.py", line 543, in __getitem__
    return self._lines[index].rstrip(os.linesep)
AttributeError: 'list' object has no attribute 'rstrip'
```

The problem here is that I request a slice `run.output[-3:]` and not a concrete index like `run.output[-3]`.  
`self._lines[index]` will then be a list and not a string, hence the error message.

The relevant documentation for that language feature (I never knew how this works internally before neither):
<https://docs.python.org/3/reference/datamodel.html#object.__getitem__> (explains that slice objects are allowed as input)
<https://docs.python.org/3/reference/datamodel.html#index-65> (explains what slice objects are)

I am not sure what the best fix would be, to me it looks wrong to even `rstrip` the separator. If we do, stripping with `os.linesep` seems to be wrong too because we do not know whether runexec was executed on the same OS with the same line separator as the OS where we execute benchexec.

**Comment by MartinSpiessl** [comment]
Well we have `any_line_contains` for that, don't we? Granted, that does only do a substring match and not a full match of a line, but should be sufficient.

In python when I iterate over lines in files I also get the line separators inside the lines. I agree that this is an inconvenience, if we keep the line separators then we had the same behavior like when iterating over the lines in a file, which would be more natural for me. And that solution also naturally solves the slicing problem.

**Comment by PhilippWendler** [comment]
Making slicing work is easy no matter what, so this is not an argument. Thanks for reporting this bug!

The arguments for removing the `rstrip` do not seem strong enough to introduce yet another breaking change.
