### ISSUE TITLE
How to pass environment variables to process being run (runexec)?

### ISSUE THREAD

**Issue by cajomferro** [sosy-lab/benchexec#620]
Hello!

I am trying to execute `runexec` with a custom python tool, called `myapp`. It seems that the Python path is not passed to the subprocesses unless I define it explicitly as below. Is there a better alternative?

```
PYTHONPATH=/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/home/mytest/.local/lib/python3.8/site-packages:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages runexec -- myapp
```

**Comment by PhilippWendler** [comment]
`runexec` should give a copy of the current environment to the tool by default. You could test this easily with `PYTHONPATH=... runexec env` and then looking at `output.log`. Depending on how you installed BenchExec (virtual env, pip, etc.) it might be the case that some auto-generated wrapper script for `runexec` sets and overwrites `PYTHONPATH`, in which case `runexec` could only pass that on to the tool, of course.

In such a case the easiest workaround could be `runexec env PYTHONPATH=... myapp`.

**Comment by cajomferro** [comment]
Thank you! It works with your workaround suggestion.
