### ISSUE TITLE
Fix input fields for numerical values of filters via the filter menu

### ISSUE THREAD

**Issue by lachnerm** [sosy-lab/benchexec#651]
When applying a filter via the filter menu for columns with numerical values, there are input field below the sliders to define the lower and upper bounds of the filter. Those input fields correctly display the currently selected bound of the filter and also update when using the slider, but **there are bugs when manually writing numerical values into those input fields**. When trying to do so, the value automatically jumps to some other value and it's not possible to apply the desired changes. 

Additionally, when hovering over the input field, there are some arrows that can be used to increase or decrease the corresponding boundary. However, **those arrows do indeed increase the value of the input field and move the slider, but the filter itself does not change**. Changes in filters can only be applied when using the slider.

Currently, the table doesn't crash or show error messages, but we should still fix both features when they are already available.

**Comment by PhilippWendler** [comment]
@DennisSimon Will you have enough time to work on this?

**Comment by DennisSimon** [comment]
@lachnerm Thank you for reporting this ~bug~ feature. 
@PhilippWendler Yes, i should be able to find some time at the end of this week
