### ISSUE TITLE
Unexpected behavior of tool_locator.find_executable

### ISSUE THREAD

**Issue by danieldietsch** [sosy-lab/benchexec#653]
I see a strange behavior, which might be a bug in ``tool_locator.find_executable``:

If I do not use ``--tool-directory .`` as argument, benchexec fails to find ``Ultimate.py`` in the current directory, although it is present. But it somehow finds a Ultimate.py somewhere else. Possibly because it checks the content of ``PATH`` first, and there is a ``Ultimate.py`` in the path.  
```
/storage/repos/ultimate/releaseScripts/default/UAutomizer-linux (dev) $ /storage/repos/benchexec/bin/benchexec --no-container --no-compress-results --maxLogfileSize=-1 --numOfThreads=14 ../benchexec/student-accelerator-lt30-svcomp.xml -d
2020-11-06 21:22:06,918 - DEBUG - This is benchexec 3.4-dev.
2020-11-06 21:22:06,936 - DEBUG - Benchmark '../benchexec/student-accelerator-lt30-svcomp.xml' is started.
2020-11-06 21:22:06,936 - DEBUG - I'm loading the benchmark ../benchexec/student-accelerator-lt30-svcomp.xml.
2020-11-06 21:22:06,943 - DEBUG - I'm loading some columns for the outputfile.
2020-11-06 21:22:31,405 - DEBUG - Looking in /storage/repos/ultimate/releaseScripts/default/adds for Ultimate and plugins/
Error: ERROR: Did find a Ultimate.py in /storage/repos/ultimate/releaseScripts/default/adds but no 'Ultimate' or no 'plugins' directory besides it
```

I am using benchexec from this branch: https://github.com/sosy-lab/benchexec/pull/652

**Comment by PhilippWendler** [comment]
This is not really related to `tool_locator.find_executable`, this has always been the way how `benchexec` looks for tools. Do you suggest to change that? Which behavior would you prefer and why?

If we change the behavior, we can do this only in a major version of BenchExec.

**Comment by danieldietsch** [comment]
I would expect to search first in the current working directory and then in ``PATH``. It is unexpected because all major OS do it differently (first current directory, then path).

**Comment by PhilippWendler** [comment]
> I would expect to search first in the current working directory and then in `PATH`. It is unexpected because all major OS do it differently (first current directory, then path).

Well, Linux (the only OS that BenchExec supports) only searches in `PATH` and does not consider `.` at all, so there is no simple precedent that we can follow.

Given that the current behavior has existed for years, I would tend to keep it until we have a clear advantage of changing it.

> EDIT: If I specify `--tool-directory`, I would expect that only the content of `tool-directory` is considered

Yes, this is the case.

**Comment by danieldietsch** [comment]
Really? Linux always tries to execute a binary with the same name in ``.`` before ``PATH``. Actually, ``PATH`` is the last place. Afair remember the order is (disregarding aliases and parameter expansion and all that): 
* shell functions
* shell builtins
* hash tables (i.e., current directory) 
* `PATH`

You can try with ``type`` for yourself.

**Comment by PhilippWendler** [comment]
Ahm, no? This is definitely not correct. If this happens on your system, then something has configured this accordingly by adding the current working directory to `PATH` as described [e.g. here](https://stackoverflow.com/q/27188856/396730).

> You can try with type for yourself.

Exactly, and it confirms my claim:
```
$ ls -l cpa.sh
-rwxr-xr-x 1 wendler wendler 5852 Jun  8 09:36 cpa.sh
$ type cpa.sh
-bash: type: cpa.sh: not found
```

**Comment by danieldietsch** [comment]
After more research, I concede. You are right, Linux does not consider the current working directory. I just remembered that ``PATH`` is the last place which is considered and somehow thought that the hash table would consider the cwd, but it does not.

Ok, in this case I just have to live with the change for me (the old "custom" tool location code of Ultimate considered the working directory first).
