### ISSUE TITLE
Add pagination to hash routing of HTML tables

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#657]
Almost all state of the HTML table is handled by adding to the hash part of the URL such that one can use the browsers back button and create links to specific views. One part that is not handled this way is the pagination (both the page size and the currently shown page). For consistency and usability it would be nice to add this (e.g., pressing back on the second page of the table will jump to the previously opened tab instead of the previous page of the table).

**Comment by lachnerm** [comment]
This feature is now added with the update of `react-table` to v7 in 1e50f3eb058fec9a4dbc31a2c3c9304f6944baae and the corresponding fix in 8392b0b00a80b1ba49eb02fef63b3385a9301988.
