### ISSUE TITLE
Allow specifying initial state for hash routing

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#658]
It would be nice if table-generator would be able to insert a string into the generated HTML file that would be used as source of initial state for the table if it is opened without a hash part in the URL. Ideally, this would
- work no matter which parameters are set in the URL and need no changes when more parameters are added,
- be ignored if table is opened with empty hash part (`...table.html#` or `...table.html#/` or a similar syntax) such that there is still a way to open it with default state,
- apply the settings before the UI is rendered for the first time in order to not confuse the user with a short flash of different content, and
- modify the hash part of the URL when being applied, such that it is visible in the URL bar afterwards.

More concrete example: After running table-generator with a to-be-added parameter like `table-generator ... --initial-table-state '/table'` and opening the produced HTML table, our code should change the content of the URL bar to `...#/table` and produce an initial view of the table that looks as if this URL would have been specified by the user.

How and where the string is added to the generated table source does not matter for table-generator, we can decide this based on what is the easiest way for the JS code. I would then take care of the integration in table-generator.

**Comment by lachnerm** [comment]
Are there any restrictions on what this string should look like? If not, would there be anything against requiring the string to match the way our URL parameters are defined, e. g. 
`--initial-table-state 'scatter?toolX=0&columnX=3&scaling=Linear&results=All&line=10000'`?
If we implement it like this, we don't really need any pre-processing of the string (expect for error checking) and can more or less just append it to the URL. We also wouldn't need to maintain the processing-function in case new URL parameter features are added to the table.

**Comment by PhilippWendler** [comment]
Yes, this is exactly what I had in mind.
