### ISSUE TITLE
Weird NaN values in data points in score-based quantile plots

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#728]
[This plot](https://buildbot.sosy-lab.org/cpachecker/results/predicate-linear/01024.-r_integration-predicate-linear.2021-04-27_23-04-18.results.html#/quantile?scaling=Linear&selection=cputime) has obviously wrong data points where the x value is set to `NaN` according to the tool tip:
![grafik](https://user-images.githubusercontent.com/2545335/116413331-ccf1d300-a837-11eb-90bc-1f3e91e4e8ee.png)
The y values contain valid values that are expected to be present in the plot.

It also occurs for some other plots, but not for our example table. Other kinds of quantile plot do not show this behavior, only the score-based quantile plot.

It occurs in BenchExec 3.7, not clear when this started.

Thanks to @kfriedberger for reporting this.

**Comment by PhilippWendler** [comment]
@lachnerm Could you please work on this when you have time (higher priority than the other tasks)? Thanks!

**Comment by lachnerm** [comment]
The problem here is that the data contains a runset for which only some of the rows have a score. The current implementation expects that if any of the rows of a runset have a score, all others do as well. This breaks the plot.
How are we supposed to handle these cases? Do we simply exclude them from the score-based plot?

**Comment by PhilippWendler** [comment]
Ok, the assumption that scores are always available for all tasks or none is invalid, it should never have been made. I think we can simply hide that run set from the score-based quantile plot, and if no run set exists with scores for all tasks, then just do the same as if there were no scores at all.
