### ISSUE TITLE
Refactor filter parsing in JS code

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#731]
In the HTML tables, filter state is stored (like other state) in URLs and thus serialized in string form. It seems that deserialization and parsing occurs more often than necessary and with duplicated code, which is highly error-prone. For example, the code `.split("_")` for separating a filter id into pieces occurs already four times (in `ReactTable.js`, `utils.js`, `FilterBox.js`, and `filters.js`), and #730 is adding more cases.

This should be refactored such that there is no code duplication and ideally each string is used only once and converted into a proper object-oriented representation, and the latter is used by the rest of the code.

**Comment by EshaanAgg** [comment]
Hi! Is this issue open for contribution? I would love to take a stab at the same.

**Comment by PhilippWendler** [comment]
Yes, AFAIK nobody is working on this.

Note that for a refactoring like this it is crucial that it does not change the behavior of the application. It would be good to first look at the existing tests to see whether they cover everything, and if not, then adding more tests that can then serve as regression tests during the refactoring.

**Comment by EshaanAgg** [comment]
Okay sir, thank you! Will explore all the relevant files and functions tonight, and post my progress here.
