### ISSUE TITLE
Overlays in HTML tables should restrict where browser search and text selection works

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#735]
I sometimes have the need to open a HTML table, click on some logfile or source code link, and search only within the open overlay pane. I would like that in that case `ctrl+f` only searches within the overlay and does not match anything in the hidden content of the table in the background. The same applies for `ctrl+a` which should select only the current logfile content and not the whole table.

Maybe there is an elegant option in HTML/JavaScript to set the current overlay pane as an active range. Maybe the following literature is related:
- https://stackoverflow.com/questions/24553251/is-it-possible-to-restrict-the-range-of-select-all-ctrla
- https://docs.w3cub.com/dom/range

**Comment by PhilippWendler** [comment]
For text selection, we can do this using the CSS property [`user-select`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select), which is a much nicer solution than overriding and reimplementing the behavior of <kbd>Ctrl+A</kbd> with JS (reimplementing browser features in JS is a strong anti-pattern). This is implemented now.

However, there does not seem to be a way for restricting the browser search, and again we don't want to do this with our own search in JS, especially given that this would not work if the user triggers browser search by some other UI method. So unfortunately this part of the feature request cannot be implemented.
