### ISSUE TITLE
Feature request: merging tables of different benchmark sets

### ISSUE THREAD

**Issue by tautschnig** [sosy-lab/benchexec#738]
Apologies if this is already available and I just failed to find the right option: `table-generator` nicely combines multiple runs over the same set of benchmarks into a single table to compare results. This works really well. If, however, trying to combine multiple runs over distinct sets of benchmarks, the output still works, but is a lot less meaningful. What I would hope to be able to produce are tables broadly resembling what @dbeyer creates in SV-COMP as the "All" result report. This would be really helpful, because one could then filter for, e.g., "wrong" results across all categories.

**Comment by PhilippWendler** [comment]
Yes, this is supported using `<union>` tags in the table definition: https://github.com/sosy-lab/benchexec/blob/75b38b6c4e5ab6ab7e89d243ad37fff69de26cd7/doc/table-generator.xml#L43-L55

We need to document this better, I will add a note to the table-generator docs.
