### ISSUE TITLE
HTML table heading cannot be copied in the browser

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#741]
I want to be able to mark details in the bold heading of a table generated by table-generator, e.g.:
https://buildbot.sosy-lab.org/cpachecker/results/predicate-bitprecise/01100.predicate-bitprecise.diff.html#/

In this table there is the following text written at the top of the last run collection:
**CPAchecker 2021-07-13 01:54:50 CEST integration-p...**

I tried to mark by mouse and copy the timestamp which didn't work. So I need to switch to the summary tab (where the bold headings are also not markable). There then I need to find the right field which displays the time and then mark this field.

**Comment by PhilippWendler** [comment]
That happens to be implemented as side effect by #719 and will work in the next release of BenchExec.
