### ISSUE TITLE
Scores in SV-COMP tables, concurrency witnesses and `mergeBenchmarkSets.py`

### ISSUE THREAD

**Issue by danieldietsch** [sosy-lab/benchexec#755]
Apologies if this is the wrong issue tracker, but since the script is here I thought it might apply. 

I just started experimenting with `mergeBenchmarkSets.py` to get correct scores for witnesses and noticed that for ConcurrencySafety, all `TRUE` results are counted as correct-unconfirmed, although there is no validator (to the best of my knowledge) that supports correctness witnesses for concurrency. 

In SV-COMP 2021, the scoring did reflect this. Is there some other version of the script that replicates this behavior? 

Also, I saw that SV-COMP has a `raw_score` column. Do you know how I can add this column to tables generated with `table-generator`?

**Comment by PhilippWendler** [comment]
For questions about `mergeBenchmarkSets.py` this is the correct place, yes.
@dbeyer @MartinSpiessl @SvenUmbricht might be able to answer this question.

`table-generator` can add [additional columns](https://github.com/sosy-lab/benchexec/blob/main/doc/table-generator.md#column-features), but only if the column value can be extracted from the run logs, which is not the case here. So this was handled by inserting column tags for `raw_score` into the result XML before passing it to `table-generator`. I am not aware of the respective script being public yet, but AFAIK the plan is to put all these scripts into the [competition-scripts](https://gitlab.com/sosy-lab/benchmarking/competition-scripts/) repository at some point.

**Comment by PhilippWendler** [comment]
If there is nothing left to with regards to this repo, I would prefer to close it. But you can file an issue over at competition-scripts, of course (though the plan is to make this code public anyway).
