### ISSUE TITLE
Upgrade to react-router 6

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#805]
We are using react-router 5 in our HTML table, and [version 6 has been released](https://remix.run/blog/react-router-v6). Upgrading needs some work on our side ([guide](https://reactrouter.com/docs/en/v6/upgrading/v5)).

We have to replace `<Switch>` with `<Routes>` and change a few things inside it, but this seems easy.

More complicated is that we use the `useHistory` hook to `listen` on history changes in `ReactTable.js`, and `useHistory` is gone now. We might be able to use [`useLocation`](https://reactrouter.com/docs/en/v6/api#uselocation) or the [`history` package](https://www.npmjs.com/package/history) that is used by `react-router`.

However, we also directly access the browser history in some other components and do `window.history.pushState()` and `window.addEventListener("popstate", ...)`, and sometimes we also access the `history` property from `react-router`, which also seems to be gone. So this also needs changes and we should probably rewrite all this history handling to use the same kind of code based on react-router.

**Comment by s2ahil** [comment]
I am a full-stack web developer I work with react. I want to work on this issue.

**Comment by PhilippWendler** [comment]
That's great! Have a look at our [readme](https://github.com/sosy-lab/benchexec/tree/main/benchexec/tablegenerator/react-table) for JS development, and if you have any questions, please ask. Questions that are specific to this issue can be asked here, for other questions please open a new issue or discussion.

**Comment by s2ahil** [comment]
Im aiming for gsoc 2024 , so can I apply this issue for gsoc If I want to contribute in sosy-lab.

**Comment by Anujvaid45** [comment]
Hi @PhilippWendler , I am Anuj, A full stack developer from India.
I have understood the issue and would like to work on it

**Comment by PhilippWendler** [comment]
Hi, any help is welcome!
