### ISSUE TITLE
Refactor setHashSearch in JS code

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#807]
The method [`setHashSearch`](https://github.com/sosy-lab/benchexec/blob/2695205de2376efb3b519b7dc5d1770825c9f0d3/benchexec/tablegenerator/react-table/src/utils/utils.js#L229) is not well designed and should be refactored.

It implements both the creation of the new hash string as well as (optionally) two(!) different side effects of what to do with the string. So the method should be split into the side-effect-free string creation and (if necessary) other methods handling the side effects. In this regard #805 and the avoiding of manual history manipulation could be relevant.

Furthermore, the method is not used well, because for example the method offers the `keepOthers` feature, which only some callers use. The other calls manually merge old and new hash params into a dict before, which could be replaced with setting `keepOthers` to `false`. And if I did not overlook something, there actually does not exist a use case for `keepOthers = false`, so this could be removed.

But first we need more tests for this method.

**Comment by EshaanAgg** [comment]
Hi! Can I work on this issue?
