### ISSUE TITLE
Timelimit in seconds or miliseconds in runexec?

### ISSUE THREAD

**Issue by hmqq** [sosy-lab/benchexec#808]
Hi,

I am working with runexec to limit single tool resources and when I gave 900 seconds (15 minutes) it takes less than 1 minute to kill the process but when I give 900000 milliseconds it takes 15 minutes and execute the tool.

I want to ask does it take a time limit in seconds or milliseconds?

Thanks!

**Comment by PhilippWendler** [comment]
RunExec supports different units for time limits, specifically `s`, `min`, `h`, and `d`. If you do not specify a unit, it uses seconds as documented by `runexec -h`. It currently does not support milliseconds.

However, if you specify millseconds, it fails as it should:
```
$ runexec --timelimit "900 ms" echo test
runexec: error: argument --timelimit: invalid parse_timespan_value value: '900 ms'
```
How did you specify milliseconds such that this did not happen?

**Comment by PhilippWendler** [comment]
Does this answer your question? Is anything still left open?

**Comment by hmqq** [comment]
Yes, it does answer my question. Thank you for clearing this up.
