### ISSUE TITLE
CSV results are difficult to process programmatically

### ISSUE THREAD

**Issue by shonfeder** [sosy-lab/benchexec#827]
When distinct sets of results are reported in a CSV, each set of data is reported in a different set of columns. As an illustration:

![image](https://user-images.githubusercontent.com/19820422/167060992-43ab5e8b-0c5f-441f-bb0d-5ebae0d0e9ef.png)

Note how the experiments on rows 4 to 8 have their results reported in columns G to J, but then the experiments on rows 9 to 13 have their results in columns C to F. As new datasets are added, we'll get more and more columns. AFAICT, it doesn't seem like this should be needed, since a column could just be added to indicate which group a row is associated with.

But the problem I'm hitting is that this makes it difficult to process the csv files programmatically. A script cannot simply process the rows of data, but instead has to be able to accommodate a variable number of columns, even tho the same kind of data gets repeated over and over in these different sets of columns.

I think data shaped like this would be much easier to manage:

![image](https://user-images.githubusercontent.com/19820422/167061586-2daee6df-38a2-4f96-8284-33a349cf6c47.png)

But I'd be interested to learn if I'm missing something.

**Comment by PhilippWendler** [comment]
Note: This has nothing to do with the CSV results specifically, the HTML table has the same layout. Or are you saying that you see different layouts between HTML and CSV? That would be a bug.

The most common use case for giving table-generator more than one result file is for comparing these results, e.g., for different tools, different configurations, etc. Thus it puts them side-by-side, with all results for a specific task in the same row.

If you have the results for a single tool/config/etc. split over several result files with distinct results, you need to use a table-definition file with a [`<union>` tag](https://github.com/sosy-lab/benchexec/blob/624b068aea652dafa3bc7e93603d5c533c7aadb7/doc/table-generator.xml#L43-L55) to tell table-generator to interpret them as a single result set. It is also possible to use several `<union>` tags to have both, i.e., several groups of column, each with results from several result files.

Does this solve your use case?

**Comment by PhilippWendler** [comment]
I am closing this because I think this is covered. If you still would like to request some changes or have further questions, please comment and reopen.
