### ISSUE TITLE
Process-termination logic of runexec not safe regarding frozen processes

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#840]
BenchExec fails to terminate processes if they are "frozen" using the freezer cgroup. This leads to an infinitely hanging run.

Typically, this cannot occur because processes inside runs cannot access cgroups and thus cannot be frozen (except if some outside process interferes with our processes and cgroups, in which case all hope is lost). However, if using `--no-container` or something like `--full-access-dir /sys/fs/cgroup` this is possible. While in principle, giving cgroup access to the executed tool is unsafe (it can easily avoid all limits, for example) there are reasonable scenarios where cgroup access is desired, in particular if the user trusts the executed tool to not maliciously fiddle with the cgroups. For example, some users nest runexec inside runexec and allow the inner runexec to access cgroups. In such a case, even a non-malicious process with cgroup access (the inner runexec) can accidentally lead to frozen processes that will trigger this problem. So runexec should be able to cope with frozen processes when killing processes.

A concrete example where this causes trouble for users of nested runexec is the following scenario:
1. runexec A starts runexec B, which starts process C.
2. B's time limit elapses, so it starts killing C. To do so, [it first freezes the cgroup of C](https://github.com/sosy-lab/benchexec/blob/5f48889dfa52d5ac130bdd38e4d9c8ff6940cbfb/benchexec/cgroups.py#L488-L490).
3. A's time limit elapses, so it starts killing B and all other (transitive) child processes. To do so, it freezes the cgroup of B (which applies to all processes in sub-cgroups as well), sends the kill signal to B and C, and unfreezes the cgroup of B.
4. B is immediately terminated after its cgroup is unfrozen.
5. Process C is still frozen because its cgroup is frozen from step 2 and this was not reverted. So process C will hang around until it is unfrozen.
6. Process C will never be unfrozen because while B would do this, B is already killed.
7. A hangs waiting for C to be killed in a [loop](https://github.com/sosy-lab/benchexec/blob/5f48889dfa52d5ac130bdd38e4d9c8ff6940cbfb/benchexec/cgroups.py#L222-L246) and repeatedly sends kill signals to C and logs messages with `Run has left-over process with pid ...`.

To solve this, runexec needs to make sure that when it attempts to kill processes, it recursively unfreezes all cgroups that exist below the run's cgroup. In the above scenario this would mean that in step 3 not only the cgroup of B is unfrozen, but also the cgroup of C, and thus C is terminated in step 4.

**Comment by danieldietsch** [comment]
We have also observed this problem when running BenchExec inside Linux containers.

**Comment by PhilippWendler** [comment]
@danieldietsch Hm, I am not sure that this is the same problem. When you just run BenchExec inside another container, typically nothing except BenchExec itself would freeze processes and this problem would not occur. Can you please explain your setup more precisely?

**Comment by danieldietsch** [comment]
I did not debug it extensively, I just noticed that under certain circumstances, (7) occurs and we need to terminate all processes manually. 

Our setup is using benchexec inside an LXC on Proxmox. LXC/Proxmox also uses cgroups to isolate containers from each other.

The issue happens not very often, so we did not try and debug it.

**Comment by PhilippWendler** [comment]
Ok, this does not sound like the current problem. First, I guess that nothing in your setup except BenchExec actually freezes processes (why should it?). Second, even if LXC freezes your whole container, it would also freeze (and unfreeze) BenchExec together with the other processes. It would certainly not descend deep(er) into the cgroup hierarchy inside the container and just freeze some processes there. So please open a new issue when you have more information.
