### ISSUE TITLE
Running just result determination on existing tool logfiles?

### ISSUE THREAD

**Issue by rmonat** [sosy-lab/benchexec#843]
Hi,

I ran benchexec on an extensive set of benchmarks. Following the completion of the job, I discovered there was a bug in my tool-info script that determines the result. Is there an easy way to ask benchexec to determine the results, without running my tool again but by using already existing logfiles?

**Comment by PhilippWendler** [comment]
Unfortunately no, there is currently no easy way to do this.

You can do this manually by editing the resulting `*results*.xml.bz2` files, there is a `<run>` tag for every run and a `<column title="status">` tag for the value that you want to change. If there is only a low number of results to change or if you write a small script (e.g., with `xmlstarlet` to edit the XML) this should be doable.

To execute the tool-info module on logs, you can unzip the logs and then use `python3 -m benchexec.test_tool_info $TOOL --tool-output $LOGFILE`.

**Comment by rmonat** [comment]
Thank you for your help!
