### ISSUE TITLE
Podman + Benchexec: Failed to configure container: [Errno 13] mount(None, b'/tmp/Benchexec_tool_info_container_b2xwyzw1', b'tmpfs', 0, b'size=100%') failed: Permission denied

### ISSUE THREAD

**Issue by blizzard4591** [sosy-lab/benchexec#889]
I am trying to run benchmarks with BenchExec - my host system is Debian Bullseye running Kernel 6.0 (from Backports). Because tools from SV-COMP23 now are build against Ubuntu 22.04, e.g. Symbiotic does not work out of the box anymore (GLIBC is too old).
So, I looking to use Podman + Benchexec. My understanding is based on the documentation, but I have the feeling I am not doing things as intended.

I have BenchExec at `/scratch/bench-defs` with my benchmarks under `/scratch/bench-defs/custom-benchmarks/CodeModifications`. This includes a run configuration in the form of `setupSYMB.xml` with the usual stuff and options.
I started my container with `podman run -dt -v /scratch:/scratch:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw --security-opt unmask=/proc/* --security-opt seccomp=unconfined docker.io/library/ubuntu:22.04`. Then I went and installed all packages necessary for BenchExec as well as BenchExec itself. Is this correct? It feels very much not so.

Now, to start a benchmark I use `scripts/execute_runs/execute-runcollection.sh benchexec/bin/benchexec archives/2023/symbiotic.zip custom-benchmarks/CodeModifications/setupSYMB.xml witness.graphml .graphml custom-results/CodeModifications_SYMB/ --read-only-dir / --read-only-dir /home --overlay-dir ./ --overlay-dir /tmp --full-access-dir /sys/fs/cgroup`.
This crashes with  `Error: Failed to configure container: [Errno 13] mount(None, b'/tmp/Benchexec_tool_info_container_b2xwyzw1', b'tmpfs', 0, b'size=100%') failed: Permission denied`. This error goes away when I use `--no-container`.
I already added the `--overlay-dir /tmp`, but this did not help/change the outcome.

What am I doing wrong? Is there a best practice on how to use BenchExec inside of containers?

Edit: I tried recreating everything as not to taint anything, and now I get a little further:
```
2022-12-30 15:03:03 - WARNING - Home directory in container should be /home/benchexec but this directory cannot be created due to directory mode of parent directory. It is recommended to use '--overlay-dir /home' or '--hidden-dir /home' and overwrite directory modes for subdirectories where necessary.
Error: Failed to configure container: [Errno 1] mount(b'proc', b'/proc', b'proc', 0, None) failed: Operation not permitted
```
Note: The warning is not very interesting, since using `--overlay-dir /home`produces the same output.

The output of `df -h` looks like this:
```
Filesystem                Size  Used Avail Use% Mounted on
fuse-overlayfs            148G  5.8G  142G   4% /
/dev/mapper/vg01-scratch  275G   63G  199G  24% /scratch
tmpfs                      64M     0   64M   0% /dev
tmpfs                      26G   56K   26G   1% /etc/hosts
shm                        63M     0   63M   0% /dev/shm
tmpfs                     4.0M     0  4.0M   0% /sys/fs/cgroup
```

**Comment by blizzard4591** [comment]
Following the discussion in https://github.com/containers/podman/discussions/16558#discussioncomment-4197726, I checked `/proc` and it shows all files as owned by nobody:nogroup. Even using `--security-opt unmask=ALL` does not change this.

**Comment by PhilippWendler** [comment]
> I am trying to run benchmarks with BenchExec - my host system is Debian Bullseye running Kernel 6.0 (from Backports). So, I looking to use Podman + Benchexec. My understanding is based on the documentation, but I have the feeling I am not doing things as intended.

What version of Podman are you using?
The instructions in the BenchExec documentation have been tested with Podman 3.4.4 on Ubuntu 22.04, and there it is working (just double checked). If your Podman is older, you might try upgrading. If your Podman is newer, there might be additional command-line flags needed.

> I started my container with `podman run -dt -v /scratch:/scratch:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw --security-opt unmask=/proc/* --security-opt seccomp=unconfined docker.io/library/ubuntu:22.04`. Then I went and installed all packages necessary for BenchExec as well as BenchExec itself. Is this correct? It feels very much not so.

Are you sure you are actually working inside the container?
Your command only starts a container in the background (`-d`), so afterward the start you would first need to access the container in order to do some work in it.

> Now, to start a benchmark I use `scripts/execute_runs/execute-runcollection.sh benchexec/bin/benchexec archives/2023/symbiotic.zip custom-benchmarks/CodeModifications/setupSYMB.xml witness.graphml .graphml custom-results/CodeModifications_SYMB/ --read-only-dir / --read-only-dir /home --overlay-dir ./ --overlay-dir /tmp --full-access-dir /sys/fs/cgroup`. This crashes with `Error: Failed to configure container: [Errno 13] mount(None, b'/tmp/Benchexec_tool_info_container_b2xwyzw1', b'tmpfs', 0, b'size=100%') failed: Permission denied`. This error goes away when I use `--no-container`.
> I already added the `--overlay-dir /tmp`, but this did not help/change the outcome.

An overlay for `/tmp` is not recommended because typically a clean `/tmp` is a good thing to have in the container of BenchExec. But this is not relevant to the problem.

> Edit: I tried recreating everything as not to taint anything, and now I get a little further:
> 
> ```
> Error: Failed to configure container: [Errno 1] mount(b'proc', b'/proc', b'proc', 0, None) failed: Operation not permitted
> ```

> Following the discussion in [containers/podman#16558 (reply in thread)](https://github.com/containers/podman/discussions/16558#discussioncomment-4197726), I checked `/proc` and it shows all files as owned by nobody:nogroup. Even using `--security-opt unmask=ALL` does not change this.

The ownership of files in `/proc` should not be relevant and is expected to be `nobody:nogroup`, as explained in the issue you linked. Only the unmasking of `/proc/*` is required.

Please check the mountpoints in the Podman container and verify that there is nothing mounted below `/proc`.

Apart from that, I currently do not have an idea what could be the reason because for me it is successfully working. Checking the Podman version seems to be a good idea. Maybe there is also something that Debian configures more strictly by default than Ubuntu that affects this.

**Comment by blizzard4591** [comment]
> > I am trying to run benchmarks with BenchExec - my host system is Debian Bullseye running Kernel 6.0 (from Backports). So, I looking to use Podman + Benchexec. My understanding is based on the documentation, but I have the feeling I am not doing things as intended.
> 
> What version of Podman are you using? The instructions in the BenchExec documentation have been tested with Podman 3.4.4 on Ubuntu 22.04, and there it is working (just double checked). If your Podman is older, you might try upgrading. If your Podman is newer, there might be additional command-line flags needed.

I was using podman 3.0.1 (Debian standard), and now upgraded to podman 3.4.2.

> 
> > I started my container with `podman run -dt -v /scratch:/scratch:rw -v /sys/fs/cgroup:/sys/fs/cgroup:rw --security-opt unmask=/proc/* --security-opt seccomp=unconfined docker.io/library/ubuntu:22.04`. Then I went and installed all packages necessary for BenchExec as well as BenchExec itself. Is this correct? It feels very much not so.
> 
> Are you sure you are actually working inside the container? Your command only starts a container in the background (`-d`), so afterward the start you would first need to access the container in order to do some work in it.

Yes, sorry I omitted that command from my description. Of course, I attach to the container before running commands.

> 
> > Now, to start a benchmark I use `scripts/execute_runs/execute-runcollection.sh benchexec/bin/benchexec archives/2023/symbiotic.zip custom-benchmarks/CodeModifications/setupSYMB.xml witness.graphml .graphml custom-results/CodeModifications_SYMB/ --read-only-dir / --read-only-dir /home --overlay-dir ./ --overlay-dir /tmp --full-access-dir /sys/fs/cgroup`. This crashes with `Error: Failed to configure container: [Errno 13] mount(None, b'/tmp/Benchexec_tool_info_container_b2xwyzw1', b'tmpfs', 0, b'size=100%') failed: Permission denied`. This error goes away when I use `--no-container`.
> > I already added the `--overlay-dir /tmp`, but this did not help/change the outcome.
> 
> An overlay for `/tmp` is not recommended because typically a clean `/tmp` is a good thing to have in the container of BenchExec. But this is not relevant to the problem.

Ah, it seems I misunderstood the intention of the overlay - my assumption was an overlay would hide this directory, but of course that doesn't make a whole lot of sense. Hindsight!


With the updated podman version, I still had to execute the suggested workaround `sudo chmod o+wt /sys/fs/cgroup/cpu,cpuacct/system.slice/benchexec-cgroup.service /sys/fs/cgroup/cpuset/system.slice/benchexec-cgroup.service /sys/fs/cgroup/memory/system.slice/benchexec-cgroup.service` on the host machine, then (and only then) the cgroups worked in the container. But now everything seems to be working!

Thanks for the help, I don't know why I did not try updating podman first, that should have been an obvious go-to!
