### ISSUE TITLE
Usage in EC2

### ISSUE THREAD

**Issue by Pacman99** [sosy-lab/benchexec#914]
I'm trying to determine if this tool would be helpful for a problem I'm facing. We're trying to run performance benchmarks for haskell code on an EC2 server and for the most part the results have little error. But occasionally the results will be wildly different from another set of results run a while before, and there isn't any changes to processes running on the machine. We believe this is due to resource spikes and dips with EC2 machines.
Is this a problem that benchexec could help with to ensure the cabal bench command is isolated in terms of CPU usage?

I'm also curious if it would be helpful for running benchmarks on kubernetes pods.

**Comment by PhilippWendler** [comment]
Thank you for your interest in BenchExec!

BenchExec only configures the running kernel as far as possible in order prevent run interference and enforce resource limits. But it cannot do anything beyond this, e.g., against influence from outside of the OS (frequency changes by the processor, throttled VM). So while I still recommend to use BenchExec, it will not solve this problem. Cloud resources without guaranteed resource allocation are just not really usable for reliable benchmarking. And note that even if you do get some resource guarantees, it might still be possible that the cloud service decides to migrate your VM from time to time and the performance is lower during the migration.
