### ISSUE TITLE
gathered CPU frequency information is wrong

### ISSUE THREAD

**Issue by adl** [sosy-lab/benchexec#918]
I prefer to run benchmarks with turbo-boost disabled, and CPU frequency set to the lowest frequency available, to get longer runtime (I'm measuring small runs) and prevent overheating.  On the host I'm working with, it's 1.6GHz.

```
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq 
1600000
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
1600000
$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
1600000
$ cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq 
1600000
$ cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq 
3900000
```

However even with such configuration, BenchExec records the following system information:
```
CPU: Intel Core i7-3770 CPU @ 3.40GHz, cores: 8, frequency: 3900 MHz, Turbo Boost: disabled; RAM: 16637 MB
```

I.e., the frequency displayed is the Turbo boost frequency instead of being the actual frequency used.  It seems benchexec reads 
`cpuinfo_max_freq`.  Shouldn't it be reading `caling_max_freq` instead?

**Comment by PhilippWendler** [comment]
Thanks a lot for reporting this, you are of course fully correct. Fix is committed and will be in the next BenchExec release.
