### ISSUE TITLE
tool-directory set problem

### ISSUE THREAD

**Issue by IOExceptionOI** [sosy-lab/benchexec#919]
I want to use benchexec to test the tool **"cpachecker"**, the config I set is below:

**sudo benchexec /home/lin/Public/bench-defs/benchmark-defs/cpachecker.xml --read-only-dir / --hidden-dir /run --hidden-dir /tmp**

But it returned **error:**

**Error: Could not find executable 'cpa.sh'. The searched directories were: 
  /usr/local/sbin
  /usr/local/bin
  /usr/sbin
  /usr/bin
  /sbin
  /bin
  /snap/bin
  .
  scripts
You can specify the tool's directory with --tool-directory.**

So I tried again with:

$ sudo benchexec **--tool-directory 
/home/lin/CPA_1/cpachecker/** /home/lin/Public/bench-defs/benchmark-defs/cpachecker.xml --read-only-dir / --hidden-dir /run --hidden-dir /tmp

**It returned Error: Could not find executable 'cpa.sh'. The searched directories were: 
  /home/lin/CPA_1/cpachecker/scripts**

But I did have cpa.sh under this path:

lin@Lin:~/CPA_1/cpachecker/scripts$ ls
benchmark     configViz.py  **cpa.sh**               determine-revision.py  post_processing      runexecutor.py
benchmark.py  cpa.bat       cpa_web_cloud.py     generate_coverage.py   README.md            table-generator.py
configcp.py   cpa_cloud.py  cpa_witness2test.py  mpi_portfolio.py       report-generator.py  witness_validation_web_cloud.py

I don't know what to do to solve it

**Comment by PhilippWendler** [comment]
First, please note that BenchExec is **not** intended to be run as root (i.e., with `sudo`). Running as root may make the container isolation fragile and allow tools to escape from the container.

`--hidden-dir /run --hidden-dir /tmp` are both [defaults](https://github.com/sosy-lab/benchexec/blob/main/doc/container.md#directory-access-modes) of BenchExec, there should be no need to specify them.

Now there are two ways to start debugging the problem.
1. Try without container mode, to see if containerization is the problem: `python3 -m benchexec.test_tool_info cpachecker --no-container --tool-directory /home/lin/CPA_1/cpachecker/`
2. If it works without container, try entering the container manually with `containerexec --read-only-dir / bash` and check whether the directory is there. For example, if your CPAchecker actually lies in `/tmp` via a symlink, then it would not be there, of course.

**Comment by IOExceptionOI** [comment]
Thanks a lot, after I try without container mode with `--no-container`, it seems working well. I wanna know where I can check whether the results I get is corresponding to the official results. I have viewd the  _pdf "Competition Report of SV-COMP 2023"_ , but I didn't see the results only for the category'No Data Race', is this category included in the category 'ConcurrencySafety'?
![data-race—1](https://github.com/sosy-lab/benchexec/assets/106426589/f5fceff1-6a17-4f74-8bdc-cc28aebd0432)
![data-race_2](https://github.com/sosy-lab/benchexec/assets/106426589/03650682-564f-423e-8842-decfc58232d6)

**Comment by PhilippWendler** [comment]
If it works with `--no-container`, then I strongly recommend to debug this and find out why it did not work with the default container mode. You should always use the container mode for benchmarking. In my previous comment I explained how to do this. Please report here if you have further problems or close this issue.

Your other question seems to be about SV-COMP? This is not part of BenchExec. For all information about SV-COMP, check its [website](https://sv-comp.sosy-lab.org) and the publications.
