### ISSUE TITLE
Case-insensitive filtering in HTML tables

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#924]
In our HTML tables, it is natural to be able to want to filter in a case-insensitive way, for example with regards to task names or other textual columns. We could support this via a checkbox in the filter overlay.

**Comment by kfriedberger** [comment]
It might be easier to just filter case-insensitive and to not provide the user a new checkbox for that. If any user later explicitly requests a specific feature for case-sensitive filtering, then think about adding the checkbox.

**Comment by PhilippWendler** [comment]
> It might be easier to just filter case-insensitive and to not provide the user a new checkbox for that. If any user later explicitly requests a specific feature for case-sensitive filtering, then think about adding the checkbox.

Indeed. A small internal poll in our group also produced 100% support for this, so let's proceed in this manner (as done in #1004).
