### ISSUE TITLE
CPU throttled itself during benchmarking due to overheating

### ISSUE THREAD

**Issue by ArpitaDutta** [sosy-lab/benchexec#926]
I have setup the test-comp locally in machine with the following specifications:
```
OS: Ubuntu22 server edition (Ubuntu 22.04.3 LTS)
Model name:            Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
CPU max MHz:         3600.0000
CPU min MHz:         400.0000
cpu execution threads: 8
RAM(without swap): 15Gi 
Swap: 4.0Gi 
```

The issue is that for most of the programs, I am getting this warning message:
 WARNING - CPU throttled itself during benchmarking due to overheating. Benchmark results are unreliable!

How to deal with this?

**Comment by PhilippWendler** [comment]
Well, your system is overheating and how do deal with this would depend on your hardware - improve cooling, put it in a cooler environment, clean it, anything of this might be useful depending on the hardware and its circumstances. BenchExec can not anything about it.

If you cannot improve cooling, you might get some improvement by loading the system less, i.e., reduce the number of parallel benchmarks (if you use more than one). And you can reduce the maximum frequency of the CPU, e.g., by disabling turbo boost if you have that enabled.

**Comment by ArpitaDutta** [comment]
Yes, I have already tried to provide a cooler environment for the machine. However, it does not solve the issue. 
Also, I am not running multiple benchmarks in parallel.

My suspect is related to the hardware I am using.
Is there any hardware specification for test-comp as well?

**Comment by PhilippWendler** [comment]
This is the BenchExec issue tracker, for Test-Comp please refer to the respective resources.

If your hardware always overheats when executing benchmarks and you cannot fix the hardware, the last remaining option I see is to reduce the CPU frequency and hope that helps. Of course the results will not be comparable with other machines with the same CPU anymore, but at least they should be more stable across runs on *this* machine. A better solution is of course to use a different machine that does not overheat.

**Comment by ArpitaDutta** [comment]
Thank you so much.
