### ISSUE TITLE
Support for fuse-overlayfs

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#928]
[fuse-overlayfs](https://github.com/containers/fuse-overlayfs) is a user-space implementation of overlayfs and commonly used by container solutions. While performance is expected to be lower than the kernel implementation, this should not matter much for our use cases, and it could help to get around #776. A disadvantage would be that it is a new dependency that users have to install. But we could consider it as an optional alternative to the kernel overlayfs.

**Comment by zain581** [comment]
@PhilippWendler i wanted to work on this issue , Can you explain more about it and any implementation  from where i can start .

**Comment by PhilippWendler** [comment]
Sorry, for the late response, I was ill.

I want to let you know that we might get someone from GSoC working on this project, but the decision is not yet made. Are you still interested in learning about this issue?

**Comment by PhilippWendler** [comment]
I just noticed that this will also help for another use case of BenchExec (#1067).
