### ISSUE TITLE
Suggestion: allow simultaneous execution of different run sets.

### ISSUE THREAD

**Issue by rmonat** [sosy-lab/benchexec#932]
Just an observation that could safely speed up benchexec: I have the impression that a new run set is executed only when the previous run set is fully finished.

So let's say I have a run set A with 9 tasks, and B with 7 tasks, and I allow benchexec to run on 16 threads. Currently, benchexec waits for the analysis of all tasks in A before starting B, while all those tasks could have been run in parallel.

**Comment by PhilippWendler** [comment]
Yes, this is tracked as #899. Unfortunately, it is architecturally not so easy, and I will have to work on other parts of BenchExec first.

**Comment by rmonat** [comment]
Right, sorry for the duplicate. Closing this one.
